/* ISOLATION map — edit by hand, or open editor.html and load this file.
   Placeholder. Agriculture Dome #11, reached off the far end of the TAR out
   of Dome #12. Nothing is drawn here yet beyond the flight back. */
ISO.register({
  "id": "AgriculturalDome11",
  "name": "Agriculture Dome #11//HIGH ENTROPY",
  "w": 290,
  "h": 140,
  "spawn": {"x": 121, "y": 127},
  "beacons": [],
  "props": {
    "203,28": {"rating":"a15","label":""},
    "200,29": {"dir":"right"},
    "204,29": {"title":"BROADCAST","text":"Colour bars. Nothing behind them.","label":"","circuit":"HOUSEBREAKER"},
    "204,30": {"title":"BROADCAST","text":"Colour bars. Nothing behind them.","label":"","circuit":"HOUSEBREAKER"},
    "188,32": {"dir":"right"},
    "192,32": {"dir":"right"},
    "196,32": {"dir":"right"},
    "190,35": {"dir":"right"},
    "193,35": {"dir":"right"},
    "196,35": {"dir":"right"},
    "199,35": {"dir":"right"},
    "202,35": {"dir":"right"},
    "186,37": {"title":"COMMAND RELAY","text":"Carrier lost. No traffic held.","desktop":true,"files":[{"kind":"doc","name":"Dock Escape Capabilties","folder":"Relayed Communications","pass":"","targets":[],"text":"The dock launching mechanism is screwed. Night Shift was supposed to upkeep the launcher, but apparently, they got taken out too, and so the thing is...\n\nIt's fucked.\nIt's all fucked.\nThe escape pods are functional, but they can only hold up to 5 people and, well, there's obviously more than 5 people on this ship."},{"kind":"doc","name":"Kitchen Stock","folder":"Relayed Communications","pass":"","targets":[],"text":"The journey to the mess hall isn't something I would recommend on a daily basis, mainly because it took us half a week because the main-line trams are down.\n\nThey don't seem to be down here, though. Foods intact, kitchen staff are still alive, but grumbling about the whole, lack of lights. Is engineering dead?\n\nWe're setting up an outpost in the middle of the mess hall, and getting counts of all the food. I've sent 5 people back to Command Tower with some food."},{"kind":"doc","name":"CYGNUS Communication Array Status","folder":"","pass":"","targets":[],"text":"CYGNUS has been attempting to repair the Comms Array on the roof of the Command Tower, but it's not going well. Every 30 minutes we lose power from CYGNUS trying to shock the array back into working.\n\nHe's got short-range radios working, but we still have to use the relays for anything cross sector. "},{"kind":"app","name":"GATELOCK","folder":"","pass":"","targets":[{"x":199,"y":44},{"x":199,"y":45},{"x":199,"y":46},{"x":199,"y":47},{"x":199,"y":48}],"text":""}],"card":"","cardsub":"","label":"","circuit":"HOUSEBREAKER"},
    "188,39": {"dir":"right"},
    "191,39": {"dir":"right"},
    "194,39": {"dir":"right"},
    "197,39": {"dir":"right"},
    "200,39": {"dir":"right"},
    "203,39": {"dir":"right"},
    "196,44": {"dir":"right"},
    "199,44": {"dir":"down","open":false,"locked":false,"circuit":""},
    "199,45": {"dir":"down","open":false,"locked":false,"circuit":""},
    "199,46": {"dir":"down","open":false,"locked":false,"circuit":""},
    "186,47": {"dir":"down"},
    "188,47": {"dir":"down"},
    "190,47": {"dir":"down"},
    "192,47": {"dir":"down"},
    "194,47": {"dir":"down"},
    "196,47": {"dir":"down"},
    "198,47": {"dir":"down"},
    "199,47": {"dir":"down","open":false,"locked":false,"circuit":""},
    "199,48": {"dir":"down","open":false,"locked":false,"circuit":""},
    "200,50": {"ways":[{"circuit":"ELEVATORBLOCK","rating":"a15"}],"label":""},
    "181,54": {"dir":"right","label":""},
    "186,55": {"dir":"right","label":""},
    "190,55": {"dir":"right","label":""},
    "194,55": {"dir":"right","label":""},
    "203,56": {"open":false,"locked":false,"circuit":"HOUSEBREAKER"},
    "204,56": {"open":false,"locked":false,"circuit":"HOUSEBREAKER"},
    "205,57": {"title":"EVACUATION ORDER FROM AGRICULTURAL DOME #11","text":"","desktop":true,"files":[{"kind":"doc","name":"Dome #11 Evacuation Orders","folder":"","pass":"","targets":[],"text":"COMMAND orders that all personnel assigned to the Agricultural Dome #11 FOB retreat to the Command Tower for securement. An emergency elevator tower has been deployed to the dome for this purpose.\n\nDo not let any important resources be left behind."},{"kind":"app","name":"FOB House Locks","folder":"","pass":"","targets":[{"x":204,"y":56}],"text":""}],"card":"","cardsub":"","circuit":"HOUSEBREAKER"},
    "198,61": {"dir":"right","range":3,"armed":true,"objective":"","label":"","circuit":"HOUSEBREAKER"},
    "191,71": {"wake":18,"range":0,"label":""},
    "199,74": {"dir":"right","label":""},
    "207,77": {"label":""},
    "55,81": {"dir":"right","label":""},
    "143,81": {"wake":18,"range":0,"label":""},
    "244,81": {"title":"COMMAND CONSOLE","text":"No readable record.","desktop":true,"files":[{"kind":"app","name":"ELEVATORGATE","folder":"","pass":"","targets":[{"x":244,"y":82},{"x":244,"y":83},{"x":244,"y":84},{"x":244,"y":85},{"x":244,"y":86},{"x":245,"y":86},{"x":245,"y":85},{"x":245,"y":84},{"x":245,"y":83},{"x":245,"y":82}],"text":""}],"card":"","cardsub":"","circuit":"ELEVATORBLOCK"},
    "161,82": {"wake":18,"range":0,"label":""},
    "244,82": {"open":false,"locked":false,"circuit":"ELEVATORBLOCK"},
    "245,82": {"open":false,"circuit":""},
    "199,83": {"dir":"right","label":""},
    "244,83": {"open":false,"locked":false,"circuit":"ELEVATORBLOCK"},
    "245,83": {"open":false,"circuit":""},
    "244,84": {"open":false,"locked":false,"circuit":"ELEVATORBLOCK"},
    "245,84": {"open":false,"circuit":""},
    "289,84": {"dest":"Intermission2","arrive":"","fade":false,"card":"","cardsub":"","label":"","circuit":""},
    "129,85": {"wake":18,"range":0,"label":""},
    "188,85": {"wake":18,"range":0,"label":""},
    "244,85": {"open":false,"locked":false,"circuit":"ELEVATORBLOCK"},
    "245,85": {"open":false,"circuit":""},
    "244,86": {"open":false,"locked":false,"circuit":"ELEVATORBLOCK"},
    "245,86": {"open":false,"circuit":""},
    "172,88": {"wake":18,"range":0,"label":""},
    "115,89": {"wake":18,"range":0,"label":""},
    "154,89": {"wake":12,"range":0,"label":""},
    "199,92": {"dir":"right","label":""},
    "122,93": {"label":""},
    "50,94": {"dest":"TunnelAccessRoute","arrive":"","fade":true,"card":"","cardsub":"","label":""},
    "117,94": {"wake":14,"range":0,"label":""},
    "123,94": {"wake":16,"range":0,"label":""},
    "42,95": {"dir":"right","label":""},
    "74,95": {"label":""},
    "119,95": {"wake":14,"range":0,"label":""},
    "67,96": {"dir":"right","label":""},
    "74,96": {"label":""},
    "119,96": {"wake":14,"range":0,"label":""},
    "117,97": {"wake":14,"range":0,"label":""},
    "123,97": {"wake":16,"range":0,"label":""},
    "152,97": {"label":""},
    "173,97": {"label":""},
    "196,97": {"label":""},
    "122,98": {"label":""},
    "100,99": {"wake":12,"range":0,"label":""},
    "109,99": {"wake":12,"range":0,"label":""},
    "89,100": {"wake":12,"range":0,"label":""},
    "146,101": {"wake":12,"range":0,"label":""},
    "169,101": {"wake":12,"range":0,"label":""},
    "115,104": {"wake":12,"range":0,"label":""},
    "98,106": {"wake":12,"range":0,"label":""},
    "53,107": {"dir":"right","label":""},
    "153,111": {"dir":"right","label":""},
    "120,112": {"label":""},
    "121,112": {"label":""},
    "122,112": {"label":""},
    "123,112": {"opens":"barn","label":""},
    "124,112": {"label":""},
    "125,112": {"label":""},
    "126,112": {"label":""},
    "118,113": {"label":""},
    "119,113": {"label":""},
    "120,113": {"label":""},
    "126,113": {"label":""},
    "127,113": {"label":""},
    "128,113": {"label":""},
    "152,113": {"wake":16,"range":0,"label":""},
    "160,113": {"wake":16,"range":0,"label":""},
    "166,113": {"dir":"right","range":3,"armed":true,"objective":"","label":"","circuit":""},
    "117,114": {"label":""},
    "118,114": {"label":""},
    "128,114": {"label":""},
    "129,114": {"label":""},
    "155,114": {"label":""},
    "156,114": {"label":""},
    "116,115": {"label":""},
    "117,115": {"label":""},
    "129,115": {"label":""},
    "130,115": {"label":""},
    "115,116": {"label":""},
    "116,116": {"label":""},
    "126,116": {"wake":18,"range":0,"label":""},
    "130,116": {"label":""},
    "131,116": {"label":""},
    "115,117": {"label":""},
    "122,117": {"wake":18,"range":0,"label":""},
    "131,117": {"label":""},
    "139,117": {"dir":"right","label":""},
    "143,117": {"dir":"right","label":""},
    "147,117": {"dir":"right","label":""},
    "151,117": {"dir":"right","label":""},
    "155,117": {"dir":"right","label":""},
    "158,117": {"title":"COMMAND CONSOLE","text":"No readable record.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "159,117": {"title":"Retreating","text":"It's all fucked down here. Command is recalling everyone up to the Tower for... fucking something. I don't know. Everyone is packing up before they get here. \n\nI pulled the fuse for the main house up the road. Don't need anyone getting into the relay in there.\n\n","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "114,118": {"label":""},
    "115,118": {"label":""},
    "119,118": {"dir":"right"},
    "124,118": {"wake":18,"range":0,"label":""},
    "131,118": {"label":""},
    "132,118": {"label":""},
    "139,118": {"opens":"barn","label":""},
    "141,118": {"dir":"down"},
    "145,118": {"dir":"down"},
    "149,118": {"dir":"left"},
    "152,118": {"dir":"down"},
    "155,118": {"rating":"a15","label":""},
    "156,118": {"dir":"right"},
    "168,118": {"dir":"down"},
    "114,119": {"label":""},
    "118,119": {"wake":18,"range":0,"label":""},
    "128,119": {"dir":"down"},
    "132,119": {"label":""},
    "175,119": {"dir":"left"},
    "114,120": {"label":""},
    "132,120": {"label":""},
    "114,121": {"label":""},
    "118,121": {"dir":"left"},
    "126,121": {"wake":18,"range":0,"label":""},
    "132,121": {"label":""},
    "172,121": {"dir":"left"},
    "114,122": {"label":""},
    "121,122": {"wake":18,"range":0,"label":""},
    "132,122": {"label":""},
    "114,123": {"label":""},
    "115,123": {"label":""},
    "120,123": {"wake":18,"range":0,"label":""},
    "123,123": {"dir":"down"},
    "131,123": {"label":""},
    "132,123": {"label":""},
    "168,123": {"dir":"up"},
    "115,124": {"label":""},
    "125,124": {"wake":18,"range":0,"label":""},
    "131,124": {"label":""},
    "173,124": {"dir":"up"},
    "115,125": {"label":""},
    "116,125": {"label":""},
    "130,125": {"label":""},
    "131,125": {"label":""},
    "176,125": {"dir":"down"},
    "116,126": {"label":""},
    "117,126": {"label":""},
    "129,126": {"label":""},
    "130,126": {"label":""},
    "168,126": {"dir":"right"},
    "117,127": {"label":""},
    "118,127": {"label":""},
    "128,127": {"label":""},
    "129,127": {"label":""},
    "171,127": {"dir":"up"},
    "172,127": {"dir":"right"},
    "118,128": {"label":""},
    "119,128": {"label":""},
    "120,128": {"label":""},
    "121,128": {"rating":"a15","label":""},
    "122,128": {"opens":"barn","label":""},
    "123,128": {"ways":[{"circuit":"HOUSEBREAKER","rating":"a15"}],"label":""},
    "126,128": {"label":""},
    "127,128": {"label":""},
    "128,128": {"label":""},
    "120,129": {"label":""},
    "121,129": {"label":""},
    "122,129": {"label":""},
    "123,129": {"label":""},
    "124,129": {"label":""},
    "125,129": {"label":""},
    "126,129": {"label":""},
    "164,130": {"open":false,"circuit":""}
  },
  "rows": [
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggdddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgdddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggghgggggggggggggggggggggggggggghggddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggghgHHHHHHHHHHHHHHHHHHHHHHHHHHghgggdddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggghgH____HAAAAAAAAAAAAA______Hghggggddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggghgH____H___________________Hghggggddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggghgH______________________f_Hghgggggdddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggghgH____H______________t_a_mHghggggggddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggghgH____H________________a_mHghggggggddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggghgH____H___________________Hghgggggggdddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggghgH____H__D___D___D________Hghgggggggdddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggghgH____H___________________Hghggggggggddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggghgH____HHHHHHHHHHHHHHHHHHHHHghggggggggddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggghgH________at_at_at_at_at_aHghggggggggddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggghgH____H___a__a__a__a__a__aHghgggggggggdddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggghgH____Hq__________________Hghgggggggggdddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddd||||||||ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggghgH____H___________________Hghgggggggggdddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____H_at_at_at_at_at_at_Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____H_a__a__a__a__a__a__Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____H___________________Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____H___________________Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____HHHHHHHHHHHHHHHHHHHHHghggggggggggddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH_______________t__>_____Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____H_____________>_____Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____H_____________>_____Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____HZ_Z_Z_Z_Z_Z_Z>_____Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____H_____________>_____Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____HHHHHHHHHHHHHHH_____Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggghgH____________CCCCCCHu____Hghggggggggggddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggghgH____H_______CCCCCCHHHHHHHghgggggggggdddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggghgH_(((H___________________Hghgggggggggdddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||ppppppppppppppppppppppppppppppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggghgH____H____________LH_____Hghgggggggggdddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||ppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggghgHJ___H____________LH_____Hghggggggggddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||ppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggghgH____HJ___J___J___LH_____Hghggggggggddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||ppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggghgHHHHHHHHHHHHHHHHHHHHHHH--Hghggggggggddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||ppppppppppppppppppppppppppppppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggghggggggggggggggggggggggggggIghgggggggdddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||ppppppppppppppppppppppppppppppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggghgggggggggggggggggggggggggggghgggggggdddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||ppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggghhhhhhhhhhhhhhhhhhhhhhhhgggghhggggggddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||ppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggppppggggggggddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||dddddddddddddddddddddddddddpppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggglgggppppgggggggdddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggppppggggggddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggppppggggggddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddpppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggppppgggggdddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||dddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggppppggggddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||dddddddddddddddddddddddddddddpppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggppppgggdddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggppppggddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggg|||||||||||gggggppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||dddddddddddddddddddddddddddddddpppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggg|||||||||||gggggppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||ddddddddddddddddddddddddddddddddpppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggg|||||||||||gggggppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||dddddddddddddddddddddddddddddddddpppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgg|||||E|||||ggggdppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||ddddddddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd|||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||ddddddddddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd|||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||dddddddddddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd|||||||||||dd@ddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddd||||||||ddddddddddddddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd|||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddpppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd|||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddd||||||||ddddddddddddddddddddddddddddddddddddddddpppppppdddddddddddddddddddddddddddddddd|||||||||||||||||||||||||||dddddddddddddddddddd|||||||||||dddddppppdjddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||dddddddddddddddddddddddddddddddddddddpppppppdddddddddddddddddddddddddddddddd|||||||||||||||||||||||||||dddddddddddddddddddd|||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||dddddddddddddddddddddddddddddddddddpppppppdd|||||||||||||||||||||||||||||||||||||||||||||||||||||||||dddddddddddddddddddd|||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||ddddddddddddddddddddddddddddddddddpppppppdd|||||||||||||||||||||||||||||||||||||||||||||||||||||||||dddddddddddddddddddd|||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddd|||||||||||@||||||||||||ddddddddddddddddddddddddddddddddpppppppdd||||||||||||||||||||||||||||||||||E||||||||||||||||||||||dddddddddddddddddddd|||||||||||dddddppppddddddddddddddddddddddddddddddddddddddI#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||dddddddddddddddddddddddddddddddpppppppdd||||||||||||||||||||||||||||||||||||||||||||||||||||E||||dddddddddddddddddddd|||||||||||dddddpppppppppppppppppppppppppppppppppppppppppp-%............................................",
    "dddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddpppppppdd|||||||||||||||||||||||||||||||||||||||||||||||||||||||||dddddddddddddddddddd|||||||||||dd@ddpppppppppppppppppppppppppppppppppppppppppp-%............................................",
    "dddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddpppppppdd||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||dddddpppppppppppppppppppppppppppppppppppppppppp-%...........................................[",
    "ddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||dddddddddddddddddddddddddddddpppppppdd||||||||||||||||||||E||||||||||||||||||||||||||||||||||||||||||||||||||||||||||E||||||||dddddpppppppppppppppppppppppppppppppppppppppppp-%............................................",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddpppppppdd||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||dddddpppppppppppppppppppppppppppppppppppppppppp-%............................................",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddpppppppdd|||||||||||||||||||||||||||||||||||||||dddddddddddd|||||||||||||||||||||||||||||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||dddddddddddddddddddddddddddpppppppdd|||||||||||||||||||||||||||||||||||||||dddddddddddd||||||||||||E||||||||||||||||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||#############|||||||||||dddddddddddddddddddddddddddpppppppdd||||||E||||||||||||||||||||||||||||||||dddddd0ddddd|||||||||||||||||||||||||||||||||||||dddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||#############|||||||||||dddddddddddddddddddddddddddpppppppdd|||||||||||||||||||||||||||||||||||||||dddddddddddd||||||||||||||||||||||||||||ddddddddddddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||##.........##|||||||||||dddddddddddddddddddddddddddpppppppdd|||||||||||||||||||||||||||||||||||||||dddddddddddd||||||||||||||||||||||||||||ddddddddddddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddd|||||||||||##.........##||||||||||||dddddddddddddddddddddddddd((pppp(dd|||||||||||||||||||||||||||||||||||||||dddddddddddd||||||||||||||||||||||||||||ddddddddddd@ddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddd|||||||||||##.........##||||||||||||ddddddddddddddddddddddddddppp(((pddddddddddddddd<dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddd|||||||||||#s.........++||||||||||||ddddddddddddddddddddddddddpppppppddddddddddedddddzddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddd||||@||||||##.........##||||||||||||jppppppppppppppppppppppppppppppppppppppppppppepppp(pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddd|||||||||||##.........##|||||@||||||jppppppppppppppppppppppppppppppppppppppppppppepppp(pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddd|||||||||||##.........##||||||||||||dddddddddddddddddddddddddddddddddddddddddddedddddzddddpppppppppggggggggggggggg<gggggggggggggggggggg<ggggggggppppppppdddddd<dddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddd|||||||||||#############||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddd<dddddpppppppppgggggggggggggggggggggggggggggggggggggggggggggppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddd|||||||||||#############||||||||||||dddddddddddddddddddddddddd0dddddddd0ddddddddddddddddddpppppppppgggggggggggggggggggggggggggggggggggggggggggggppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||dddddddddddddddd0ddddddddddddddddddddddddddddddddddddddpppppppppgggggggggggggggPPPPPPggggggggggggggggggggggggppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddpppppppppggggggggg0ggggPPPPPPPPgggggggggg0ggggggggggggppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddpppppppppgggggggggggggPPPPPPPPPPggggggggggggggggggggggppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddpppppppppggggggggggggPPPPPPPPPPPPggggggggggggggggggggpppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddddddddddddddd0ddddddddddddpppppppppggggggggggggPPPPPPPPPPPPggggggggggggggggggggpppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddddddddddddddddddddddddddddppppppppppgggggggggggPPPPPPPPPPPPgggggggggggggggggggppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||||ddddddddddddddddddddddddddd0ddddddddddddddddddddddddddddddpppppppppggggggggggggPPPPPPPPPPggggggggggggggggggggpppppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddd|||||||||||@||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddppppppppppggggggggggggPPPPPPPPggggggggggggggggggggppppppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||||ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddpppppppppgggggggggggggPPPPPPgggggggggggggggggggggpppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddppppppppppppppppppppppppppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddppppppppppppppppppppppppppppppppppppppppppppppppppppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddppppppppppppppppppppppRpppppppppppppppppppppppppppppppppdddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddQQQKQQQdddddppppppppppppppppppppppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddd||||||||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddQQQ_____QQQdddddppppppppppppppppppzpppppppzppppplpppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddd||||||||dddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQ_________QQddddddppppppppppppppppppp<<pppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQ___________QQdddddddppppppppppppppppppppppppppppppppppppppppppddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQ_________E___QQddddddHHHHHHHHHHHHHHHHHHHHHHHH+HHHiiiiiiiiiiiiHHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ______E________QddddddHJ__HJ__HJ__HJ__HJ__IcHL__HXXXXXXXXXXXXXXHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQ___Y____E______QQdddddHk_YH__YH__YH_Y_HfY___HL__HX;;Y;;;;;;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ___E_________Y___QdddddH___H___H___H___H_____HL__HX;;;;;;;;;Y;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ_________________QdddddH___H___H___H___H_____H__LHX;;;;;;;;;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ___Y_______E_____QdddddH___H___H___H___H_____H__LHX;;;;;;Y;;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ______E__________QdddddH___H___H___H___H_____HH_HHX;;;;;;;;;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQ____E__Y_______QQdddddH___H___H___H___H_____H___HX;;Y;;;;;;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ_________E_____QddddddH___H___H___H___H_____H___HX;;;;;;;Y;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQ_____________QQddddddH___H___H___H___H_____H___HX;;;;;;;;;;Y;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQ___________QQdddddddH___H___H___H___H_____H___HX;;Y;;;;;;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQ_________QQddddddddH___H___H___H___H_____H___HX;;;;;YY;;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQQfku__QQQdddddddddH___H___H___H___H_____H___HX;;;;;;;;;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQQQQQQQdddddddddddHHH_HHH_HHH_HHH_HHH_HHH___HX;;;;;;;;;;;;XHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddH_________________________%XXXXXXXXXXXXXXHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################",
    "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd#############################################"
  ]
});
