/* ISOLATION map — edit by hand, or open editor.html and load this file.
   Agriculture Dome #12, where the breach in the floor of Service Car 14 comes
   down. The car names this deck and fades into it, and the deck has a poem
   filed under its id in index.html, which is read out on that black before the
   dome is looked at — see **A poem held on that black** in this folder's README.

   What is drawn here is the dome and nothing else: the wall it curves round,
   the floor inside it, the plating that came down with the unit, and the
   landing plate the breach aims at, so the fall has somewhere real to end. The
   fields themselves, and the way on out of them, are not drawn yet.

   The plate at 22,14 is a beacon with its transmitter off: it says nothing and
   it does nothing, it is only stencilled DOME12-LANDING, which is the name the
   breach arrives at — that is what puts the unit down in the middle of the
   dome rather than at whatever the deck would otherwise call its landing. */
ISO.register({
  "id": "AgriculturalDome12Fields",
  "name": "Agriculture Dome #12//FIELDS",
  "w": 141,
  "h": 100,
  "spawn": {"x": 22, "y": 14},
  "beacons": [],
  "props": {
    "18,0": {"title":"Car broke down","text":"Y'know. The year is... 2300... something, and you think we would make cars that don't break down. But no! Of course they still break down."},
    "109,4": {"label":""},
    "110,4": {"label":""},
    "111,4": {"label":""},
    "112,4": {"label":""},
    "113,4": {"label":""},
    "114,4": {"label":""},
    "115,4": {"label":""},
    "106,5": {"label":""},
    "107,5": {"label":""},
    "108,5": {"label":""},
    "109,5": {"label":""},
    "111,5": {"title":"TUNNEL ACCESS ROUTE","text":"All Agricultural Domes are equipped with Tunnel Access routes or TARs that connect each dome. While TARs are legal to use, It is generally not recommended to use them without a flashlight and proper safety equipment.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "112,5": {"dest":"TunnelAccessRoute","arrive":"","fade":true,"card":"","cardsub":"","label":""},
    "113,5": {"range":2,"armed":true,"objective":"","label":"","circuit":""},
    "115,5": {"label":""},
    "116,5": {"label":""},
    "117,5": {"label":""},
    "118,5": {"label":""},
    "19,6": {"dir":"up","label":""},
    "105,6": {"label":""},
    "106,6": {"label":""},
    "118,6": {"label":""},
    "119,6": {"label":""},
    "104,7": {"label":""},
    "105,7": {"label":""},
    "119,7": {"label":""},
    "120,7": {"label":""},
    "103,8": {"label":""},
    "104,8": {"label":""},
    "120,8": {"label":""},
    "121,8": {"label":""},
    "102,9": {"label":""},
    "103,9": {"label":""},
    "121,9": {"label":""},
    "122,9": {"label":""},
    "101,10": {"label":""},
    "102,10": {"label":""},
    "122,10": {"label":""},
    "123,10": {"label":""},
    "101,11": {"label":""},
    "108,11": {"dir":"down"},
    "110,11": {"dir":"down"},
    "114,11": {"dir":"down"},
    "119,11": {"dir":"down"},
    "123,11": {"label":""},
    "101,12": {"label":""},
    "123,12": {"label":""},
    "100,13": {"label":""},
    "101,13": {"label":""},
    "123,13": {"label":""},
    "124,13": {"label":""},
    "100,14": {"label":""},
    "124,14": {"label":""},
    "100,15": {"label":""},
    "104,15": {"dir":"left"},
    "115,15": {"dir":"left"},
    "124,15": {"label":""},
    "100,16": {"label":""},
    "109,16": {"dir":"left"},
    "110,16": {"dir":"right"},
    "124,16": {"label":""},
    "16,17": {"title":"SOUTH","text":"THE MCENGLES FAMILY FARM"},
    "100,17": {"label":""},
    "117,17": {"dir":"left"},
    "124,17": {"label":""},
    "100,18": {"label":""},
    "101,18": {"label":""},
    "106,18": {"dir":"right"},
    "113,18": {"dir":"up"},
    "123,18": {"label":""},
    "124,18": {"label":""},
    "101,19": {"label":""},
    "119,19": {"dir":"up"},
    "123,19": {"label":""},
    "101,20": {"label":""},
    "109,20": {"dir":"left"},
    "116,20": {"dir":"left"},
    "123,20": {"label":""},
    "101,21": {"label":""},
    "102,21": {"label":""},
    "114,21": {"dir":"left"},
    "122,21": {"label":""},
    "123,21": {"label":""},
    "102,22": {"label":""},
    "103,22": {"label":""},
    "121,22": {"label":""},
    "122,22": {"label":""},
    "103,23": {"label":""},
    "104,23": {"label":""},
    "120,23": {"label":""},
    "121,23": {"label":""},
    "104,24": {"label":""},
    "105,24": {"label":""},
    "119,24": {"label":""},
    "120,24": {"label":""},
    "105,25": {"label":""},
    "106,25": {"label":""},
    "118,25": {"label":""},
    "119,25": {"label":""},
    "106,26": {"label":""},
    "107,26": {"label":""},
    "108,26": {"label":""},
    "109,26": {"label":""},
    "115,26": {"label":""},
    "116,26": {"label":""},
    "117,26": {"label":""},
    "118,26": {"label":""},
    "109,27": {"label":""},
    "110,27": {"dir":"right","open":false,"locked":false,"circuit":""},
    "111,27": {"dir":"right","open":false,"locked":false,"circuit":"SILO"},
    "112,27": {"dir":"right","open":false,"locked":false,"circuit":""},
    "113,27": {"dir":"right","open":false,"locked":false,"circuit":""},
    "114,27": {"dir":"right","open":false,"locked":false,"circuit":""},
    "115,27": {"label":""},
    "109,28": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":true,"files":[{"kind":"doc","name":"Locked up the Silo","folder":"","pass":"","targets":[],"text":"We should've been able to support them. We had enough food but... It just...\n\nI can't live here anymore. We got to get out this dome."},{"kind":"app","name":"SILO GATE","folder":"","pass":"Amazing Grace","targets":[{"x":110,"y":27},{"x":111,"y":27},{"x":112,"y":27},{"x":114,"y":27},{"x":113,"y":27}],"text":""}],"card":"","cardsub":"","circuit":"SILO"},
    "58,30": {"label":""},
    "58,31": {"title":"...","text":"ABANDON ALL HOPE, ALL YE WHO ENTER HERE"},
    "121,33": {"dir":"right"},
    "126,33": {"dir":"right"},
    "127,34": {"rating":"a15","label":""},
    "121,35": {"dir":"right"},
    "126,35": {"dir":"right"},
    "127,36": {"title":"AUDIO LOG: PRAYER??? FROM LUKE ENGLES","text":"Hail Mary, full of grace, the Lord is with thee.\nBlessed art thou amongst women,\nand blessed is the fruit of thy womb, Jesus.\nHoly Mary, Mother of God,\npray for us sinners,\nnow and at the hour of our death. Amen.\n\nSILENCE\n\n*Clicking Noise*\n\nWhat?\n\n*Clicking Noises\"\n\n*Door bursts open, and shuts quickly*\n\nPatricia Engles: Don't go out there.\n\nLuke Engles: Why?\n\n*Crying*\n\nP: \"Just... don't sweetie.\"","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "121,37": {"dir":"right"},
    "126,37": {"dir":"right"},
    "121,39": {"dir":"right"},
    "126,39": {"dir":"right"},
    "99,40": {"dir":"right","label":""},
    "117,43": {"ways":[{"circuit":"SILO","rating":"a15"}],"label":""},
    "127,44": {"opens":"barn","label":""},
    "109,45": {"title":"FOR ALL SEEKING REFUGE FROM D-DAY","text":"Agriculture Dome #12 isn't the biggest dome, but it is one of the only domes that is entirely self-sufficient from the rest of the ship"},
    "128,46": {"dir":"down"},
    "128,48": {"dir":"down"},
    "133,48": {"title":"BROADCAST","text":"Colour bars. Nothing behind them.","label":"","circuit":""},
    "133,49": {"title":"BROADCAST","text":"Colour bars. Nothing behind them.","label":"","circuit":""},
    "95,50": {"dir":"left","label":""},
    "128,50": {"dir":"down"},
    "112,51": {"title":"AUDIO LOG: RUNNING LOW","text":"P - Patricia McEngle\nL - Luke McEngle\n---\nP: \"See this crate?\"\n\nL: \"Yeah.\"\n\nP: \"Empty.\"\n\nL: \"What?!\"\n\nP: \"Hey! Keep your voice down, we don't need anyone else knowing right now!\"\n\nL: \"Why the hell is it empty? Wasn't Night-Shift supposed to fill it?\"\n\nP: \"Those things got Night-Shift! They must've not had time to fill up the stores. I checked, the Silo is empty too.\"\n\nL: \"What are we going to do? The corn isn't going to be ready for another month!\"\n\nP: *sigh* \"We're going to have to venture out.\"\n\nL: \"No! No way. We promised these people that they wouldn't have to do that.\"\n\nP: \"Well we promised these people food, and now we don't have that either, so what are we going to do, sit here and starve?!\"\n\nSILENCE\n\nL: \"I'll get a group and go out tomorrow. Try to hit the stores on Dome #11.\"\n\nP: \"Good.\"","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "126,54": {"dir":"right"},
    "121,60": {"dir":"right"},
    "124,60": {"title":"AUDIO LOG: YELLING AND CLICKING","text":"UNKNOWN-1: *YELLING*\n\n*Clicking Noises*\n\nUNK-2: \"NO! NO! GET AWAY!\"\n\n*Clicking Noises*\n\n[REST OF LOG REMOVED FOR BREVITY]","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "125,60": {"opens":"barn","label":""},
    "126,60": {"dir":"right"},
    "121,62": {"dir":"right"},
    "126,62": {"dir":"right"},
    "121,64": {"dir":"right"},
    "126,64": {"dir":"right"},
    "121,66": {"dir":"right"},
    "126,66": {"dir":"right"},
    "121,68": {"dir":"right"},
    "126,68": {"dir":"right"}
  },
  "rows": [
    "||||||||||||ggggppnppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggggggggQQQQQQQggggggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggggQQQQ_cs*_QQQQgggggggggggggggggggggg",
    "||||||||||||ggggpppRpppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggggQQ___________QQggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggQQ_____________QQgggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggQQ_______________QQggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggQQ_________________QQgggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggQQ______X____________QQggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggQ______YXY___Y____Y___Qggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggQ_______X_____________Qggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggQQ_______X_____________QQgggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggQ_______________________Qgggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggQ___Y_XXX______Y________Qgggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggQ_____X__YY_______X_____Qgggggggggggggggg",
    "||||||||||||gggg?ppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggQ_____XX_XXXX____YX_____Qgggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggQQ____Y__XXXXY___XX____QQgggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggQ_________X_______Y___Qggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggQ_______Y______Y______Qggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggQQ___________Y_______QQggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggQQ_________________QQgggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggQQ_______________QQggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggQQ_____________QQgggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggggQQ___________QQggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggggQQQQ_____QQQQgggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggggggggQ>>>>>Qggggggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggggggggcggggggggggggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||ggg|||||||||||||||||||||||||gggggggggghgggyyyggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||gjg|||||||||||||||||||||||||gggggggggghgggyyyg&&ggggggggwwwwgHHHHHHHHHHHHHHHgggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||g?g|||||||||||||||||||||||||gggggggggghgggyyyg&&gggggggggggggH_____________Hgggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggyyyyygggggwwwwgH_____________Hgggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggyyyyyggggggggggH__D____D_____Hgggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggyyyyyggggggggggH________f____Hgggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggggggggggggg&&gH__D____D_____Hgggggggg",
    "||||||||||||ggggpppppppppppppggg|||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggggggggggggg&&gH________c____Hgggggggg",
    "||||||||||||ggggpppppppppppppgggg||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggggggggggggyyyygH__D____D_____Hgggggggg",
    "||||||||||||ggggpppppppppppppgggg||||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggggggggggggyyyygH_____________Hgggggggg",
    "||||||||||||ggggpppppppppppppggggg|||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghgggggggggggggggggyyyygH__D____D_____Hgggggggg",
    "||||||||||||ggggpppppppppppppggggg|||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggg@ggggggggggggggggggH_____________Hgggggggg",
    "||||||||||||ggggpppppppppppppggggg|||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggggggggggggggggHL____________Hgggggggg",
    "||||||||||||ggggpppppppppppppgggggg||||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggggggggggggggggHL____________Hgggggggg",
    "||||||||||||ggggpppppppppppppgggggggg||||||||||||||||||||||||||||||||||||||||||||||||gggggggggghggggggggggggggggggggguHLLLL_________Hgggggggg",
    "||||||||||||ggggpppppppppppppgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggghggggggggggHHHHHiiHHHHHHHHHHHHHHKHHHHHHHgggggg",
    "||||||||||||ggggppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggHLLn_____BBH________________Hgggggg",
    "||||||||||||ggggppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggH_________BH__________U_____Hgggggg",
    "||||||||||||gggggpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppgggggggggggggggggggg+__________H________________Hgggggg",
    "||||||||||||gggggppppppppppppppppppppppppppppppppppppppppppppppprrrrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggH__________H__________U____mHgggggg",
    "|||||||||||||gggggppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggH__________________________mHgggggg",
    "|||||||||||||gggggpppppppppppppppppppppppppppppppppppppppppppppprrrrrrrrrrrrrrrrrrrrrrrrrggggggRggggggggggHHHHHHHHHHHH__________U_____Hgggggg",
    "||||||||||||||gggggpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggHCCCCCc____H________________Hgggggg",
    "||||||||||||||gggggpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggHCCCCC_____H________________Hgggggg",
    "|||||||||||||||ggggpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggHCCCCC_____H________________igggggg",
    "|||||||||||||||gggggppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggHCCCCC_____+_______at_a_____igggggg",
    "|||||||||||||||ggggggggpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggHCCCCC_____H_______a__a_____igggggg",
    "||||||||||||||||||gggggggpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggi__________H________________igggggg",
    "||||||||||||||||||||gggggggpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppggggggggggggggggggggi__________H________________igggggg",
    "||||||||||||||||||||||ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggghggggggggggH__________H________________Hgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggHHH++HHHHHHHHHHHHHHHHHHHHHHHHgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggH___________CC_D__ckD_______Hgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggH_______CC__CCS___S_____S__SHgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggH_______CC__CC_D____D_______Hgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggH_______CCXXCC______________Hgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggH_______CCXXCC_D____D_______Hgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggH______XCCXXCC_____S________Hgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggH______XCCXXCC_D____D______SHgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggH______XCCXXCCS_____________Hgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggHX_____SCCXXXX_D____D_______Hgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggHXX_____CCXXXX____________S_Hgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggHHHHHHHHHHHHHHHHHHHHHHHHHHHHHgggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghggggggggggggggggggggggggggggggggggggggggggggg",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
    "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||ggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"
  ]
});
