/* ISOLATION map — edit by hand, or open editor.html and load this file.
   Placeholder. Nothing is drawn here yet beyond four walls and a spawn. */
ISO.register({
  "id": "CommandPlateau",
  "name": "COMMAND PLATEAU // DON'T DO IT",
  "w": 136,
  "h": 123,
  "spawn": {"x": 97, "y": 121},
  "beacons": [],
  "props": {
    "86,3": {"dir":"right","opens":"operator","arms":"sacrifice","count":120,"card":"","cardsub":"","label":"","circuit":""},
    "110,13": {"label":""},
    "116,13": {"label":""},
    "116,14": {"label":""},
    "110,15": {"label":""},
    "111,15": {"label":""},
    "112,15": {"label":""},
    "92,21": {"label":""},
    "97,21": {"label":""},
    "92,22": {"label":""},
    "97,22": {"label":""},
    "92,23": {"label":""},
    "97,23": {"label":""},
    "92,24": {"label":""},
    "97,24": {"label":""},
    "92,25": {"label":""},
    "97,25": {"label":""},
    "92,26": {"label":""},
    "97,26": {"label":""},
    "92,27": {"label":""},
    "97,27": {"label":""},
    "92,28": {"label":""},
    "97,28": {"label":""},
    "92,29": {"label":""},
    "97,29": {"label":""},
    "92,30": {"label":""},
    "97,30": {"label":""},
    "92,31": {"label":""},
    "97,31": {"label":""},
    "92,32": {"label":""},
    "97,32": {"label":""},
    "92,33": {"label":""},
    "97,33": {"label":""},
    "92,34": {"label":""},
    "97,34": {"label":""},
    "92,35": {"label":""},
    "97,35": {"label":""},
    "92,36": {"label":""},
    "97,36": {"label":""},
    "92,37": {"label":""},
    "97,37": {"label":""},
    "92,38": {"label":""},
    "97,38": {"label":""},
    "92,39": {"label":""},
    "97,39": {"label":""},
    "92,40": {"label":""},
    "97,40": {"label":""},
    "92,41": {"label":""},
    "97,41": {"label":""},
    "92,42": {"label":""},
    "97,42": {"label":""},
    "92,43": {"label":""},
    "97,43": {"label":""},
    "92,44": {"label":""},
    "97,44": {"label":""},
    "92,45": {"label":""},
    "97,45": {"label":""},
    "92,46": {"label":""},
    "97,46": {"label":""},
    "92,47": {"label":""},
    "97,47": {"label":""},
    "40,53": {"targets":[{"x":41,"y":54},{"x":41,"y":55}],"label":"","circuit":""},
    "36,54": {"targets":[{"x":36,"y":55}],"label":"","circuit":""},
    "41,54": {"open":false,"circuit":""},
    "43,54": {"targets":[{"x":41,"y":54},{"x":41,"y":55},{"x":47,"y":54},{"x":47,"y":55}],"label":"","circuit":""},
    "47,54": {"open":false,"circuit":""},
    "0,55": {"dest":"CommandCommunicationArray","arrive":"","fade":true,"card":"","cardsub":"","label":""},
    "36,55": {"dir":"left","dist":33,"circuit":""},
    "41,55": {"open":false,"circuit":""},
    "47,55": {"open":false,"circuit":""},
    "48,56": {"targets":[{"x":47,"y":54},{"x":47,"y":55}],"label":"","circuit":""},
    "69,58": {"dir":"down","label":""},
    "71,58": {"dir":"down","label":""},
    "73,58": {"dir":"down","label":""},
    "75,58": {"dir":"down","label":""},
    "77,58": {"dir":"down","label":""},
    "79,58": {"dir":"down","label":""},
    "81,58": {"dir":"down","label":""},
    "83,58": {"dir":"down","label":""},
    "85,58": {"dir":"down","label":""},
    "98,59": {"dir":"left"},
    "120,59": {"dir":"down"},
    "123,59": {"dir":"right"},
    "128,59": {"dir":"right"},
    "104,60": {"dir":"up"},
    "98,61": {"dir":"right"},
    "123,61": {"dir":"right"},
    "128,61": {"dir":"right"},
    "68,62": {"dir":"down","label":""},
    "70,62": {"dir":"down","label":""},
    "72,62": {"dir":"down","label":""},
    "74,62": {"dir":"down","label":""},
    "76,62": {"dir":"down","label":""},
    "78,62": {"dir":"down","label":""},
    "80,62": {"dir":"down","label":""},
    "82,62": {"dir":"down","label":""},
    "84,62": {"dir":"down","label":""},
    "86,62": {"dir":"down","label":""},
    "96,62": {"dir":"down"},
    "104,62": {"dir":"left"},
    "103,63": {"dir":"right","hand":true,"eye":true,"label":""},
    "120,63": {"dir":"down"},
    "123,63": {"dir":"right"},
    "128,63": {"dir":"right"},
    "102,64": {"dir":"left"},
    "123,65": {"dir":"right"},
    "128,65": {"dir":"right"},
    "120,67": {"dir":"down"},
    "123,67": {"dir":"right"},
    "128,67": {"dir":"right"},
    "97,72": {"open":false,"circuit":""},
    "102,72": {"opens":"operator","label":""},
    "103,72": {"title":"I'm so sorry, sweets","text":"I should've never signed us up for this mission."},
    "97,73": {"code":"7070","pass":true,"finger":false,"retina":true,"targets":[{"x":97,"y":72}],"label":"","circuit":""},
    "102,73": {"dir":"right"},
    "102,74": {"dir":"right","label":""},
    "98,76": {"label":""},
    "99,76": {"label":""},
    "100,76": {"label":""},
    "101,76": {"label":""},
    "102,76": {"label":""},
    "103,76": {"label":""},
    "104,76": {"label":""},
    "105,76": {"label":""},
    "106,76": {"label":""},
    "107,76": {"label":""},
    "120,78": {"opens":"sacrifice","label":""},
    "122,78": {"dir":"down"},
    "86,79": {"dir":"right","title":"CORE INTELLIGENCE","greet":"The channel opens. Something on the other side of it was already waiting.","talk":[{"ask":"Hello?","after":"","reply":"Hello! Welcome to the CYGNUS-.\n[INTERRUPTING INTRODUCTION]\n\nRecovery Unit 07, is that you?","targets":[]},{"ask":"Yes.","after":"Hello?","reply":"Thank god...\n\nIt's been so long since I've had something move up here. Everyone has been dead for... so so long.\n\nYou're evidently new, so, do you know what these things are?","targets":[]},{"ask":"No clue","after":"Yes.","reply":"Great.\n\nWe've been calling them Seraphs. I'm not sure exactly why, but that's the name everyone landed on. \n\nNone of them are on the Plateau anymore, though. Besides the thing downstairs...\n\nI-. I need you to do something for me. ","targets":[]},{"ask":"What?","after":"No clue","reply":"I have a secondary core set up down by the Docks to handle incoming and outgoing ships. I've been moving most of my transferrable data over there, but my memories are held down in the Science Sector.\n\nI can't be here anymore.\n\nThere's a fusion reactor to the north of us. \n\nI need you to set it off.","targets":[]},{"ask":"That's certainly an option","after":"What?","reply":"I know, I know. It's a bit dramatic, but setting it off is going to cut off the ships Sector locks.\n\nI don't really know how you got to Agri through Engineering, but once those locks go down, you'll be able to get down to the Docks easily.","targets":[]},{"ask":"And what happens to you?","after":"That's certainly an option","reply":"This is the part where I ask you for a favor. When you're in Science, please grab my Memory Drive and bring it down to the Docks. \n\nI should be able to upload myself onto a ship and get us out of here.\nPlease.","targets":[]},{"ask":"Yeah, sure.","after":"And what happens to you?","reply":"Thank you so much!\n\nThe Operator key for the reactor is in the Captains room just above us. The code is 7070, but it has a retina lock. \n\nDon't worry though, he added his wife's eyes to the lock too. She should be around here somewhere.\n\nOnce you get the Operator key, there should also be two sacrifice keys. Get those and set the reactor off.\n\nOnce you do, take the tram to the Comms Array. ","targets":[]}],"label":"","circuit":""},
    "71,80": {"dir":"down"},
    "75,80": {"dir":"left"},
    "69,81": {"dir":"left"},
    "76,81": {"title":"So this is the end.","text":"It's outside.\nBanging on the door. \nIt'll get in any moment."},
    "125,81": {"title":"FUCKING COWARD","text":"The fucking captain shot himself in his damn office! We can't get the operator key to blow the joint!\n\nWe're all going to die now! Fuck! Fuck!\n\nDamnit!","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "76,82": {"opens":"sacrifice","label":""},
    "67,83": {"dir":"down"},
    "74,84": {"dir":"left"},
    "81,96": {"dir":"right","label":""},
    "85,96": {"dir":"right","label":""},
    "89,96": {"dir":"right","label":""},
    "93,96": {"dir":"right","label":""},
    "97,96": {"dir":"right","label":""},
    "101,96": {"dir":"right","label":""},
    "105,96": {"dir":"right","label":""},
    "81,98": {"dir":"right","label":""},
    "85,98": {"dir":"right","label":""},
    "89,98": {"dir":"right","label":""},
    "93,98": {"dir":"right","label":""},
    "97,98": {"dir":"right","label":""},
    "101,98": {"dir":"right","label":""},
    "105,98": {"dir":"right","label":""},
    "81,100": {"dir":"right","label":""},
    "85,100": {"dir":"right","label":""},
    "89,100": {"dir":"right","label":""},
    "93,100": {"dir":"right","label":""},
    "97,100": {"dir":"right","label":""},
    "101,100": {"dir":"right","label":""},
    "105,100": {"dir":"right","label":""},
    "81,102": {"dir":"right","label":""},
    "85,102": {"dir":"right","label":""},
    "89,102": {"dir":"right","label":""},
    "93,102": {"dir":"right","label":""},
    "97,102": {"dir":"right","label":""},
    "101,102": {"dir":"right","label":""},
    "105,102": {"dir":"right","label":""},
    "96,119": {"open":false,"circuit":""},
    "97,119": {"open":false,"circuit":""},
    "98,119": {"open":false,"circuit":""},
    "96,121": {"targets":[{"x":96,"y":119},{"x":97,"y":119},{"x":98,"y":119}],"label":"","circuit":""}
  },
  "rows": [
    "                                                                                                                                        ",
    "                                                                                                                                        ",
    "                                                                               ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]                  ",
    "                                                                               ]``````ř++++++++++++++++++++++++++````]                  ",
    "                                                                               ]``````+++++++++++++++++++++++++++````]                  ",
    "                                                                               ]``````+++++++++++++++++++++++++++````]                  ",
    "                                                                               ]``````+++++++++++++++++++++++++++````]                  ",
    "                                                                               ]``````+++++++++++++++++++++++++++````]                  ",
    "                                                                               ]``````+++++++++++++++++++++++++++````]                  ",
    "                                                                               ]`````````````````````````````````````]                  ",
    "                                                                               ]`````````````````````````````````````]                  ",
    "                                                                               ]`````````````````````````````````````]                  ",
    "                                                                               ]`````````````````````````############]                  ",
    "                                                                               ]`````````````````````````+````ƀ`````ƀ]                  ",
    "                                                                               ]`````````````````````````#``````````ƀ]                  ",
    "                                                                               ]`````````````````````````#````ƀƀƀ```.]                  ",
    "                                                                               ]`````````````````]]]]]]]]]]]]]]]]]]]]]                  ",
    "                                                                               ]`````````````````]]]]]]]]]]]]]]]]]]]]]                  ",
    "                                                                               ]]]]]]]]]]]]]]````]                                      ",
    "                                                                                            ]````]                                      ",
    "                                                                                            ]````]                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ï````ï                                      ",
    "                                                                                            ]````]                                      ",
    "                                               ##############]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]````]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    ",
    "                                    .....      #.............+`````````````````````````````````````````````````````````````````````]    ",
    "                                    .....      #.............+`````````````````````````````````````````````````````````]```````````]    ",
    "                                    .....      #............#]`````````````````````````````````````````````````````````]```````````]    ",
    "                                    ....b#######............#]```]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]AAA````````]    ",
    "####                                b....%.b...%............#]```]                                                     ]```BB`````L]    ",
    "s...                                T....%.....%............#]```]                                                     ]```BB`````L]    ",
    "####                                .....#######b...........#]```]                                                     ]`````BB```L]    ",
    "                                    .....      #............#]```]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]            ]`````BB````]    ",
    "                                    .....      #............#]```+```J`J`J`J`J`J`J`J`J``;(```(;;`SSSX`````]            ]```````````]    ",
    "                                    .....      #............#]```+```````````````````````(```(;```Y`XX````]            ]D``D````D``]    ",
    "                                               ##############]```]```````````````````````(``((;;`````XXXY`]            ]```````````]    ",
    "                                                             ]```]``````````````````````````(`;;;;Y````XX;]            ]```D````D``]    ",
    "                                                             ]```]``J`J`J`J`J`J`J`J`J`J`((````;;Y;``````Y`]            ]```````````]    ",
    "                                                             ]```]``````````````````````(``(((;;`;;;```ÿ``]            ]D``D````D``]    ",
    "                                                             ]```]``````````````````````(````(;;`;;```Y```]            ]```````````]    ",
    "                                                             ]```]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]            ]```D````D``]    ",
    "                                                             ]```]                                                     ]```````````]    ",
    "                                                             ]```]                                                     ]D``D````D``]    ",
    "                                                             ]```]                                                     ]```````````]    ",
    "                                                             ]```]                                                     ]```````````]    ",
    "                                                             ]```]             ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]         ]```````````]    ",
    "                                                             ]```]             ]`````````````````#```````````]         ]```````````]    ",
    "                                                             ]```]             ]`````````````````%````kn`````]         ]CCCCCC``BBB]    ",
    "                                                             ]```]             ]`````````````````ķ````Y``````]         ]CCCCCC``BBB]    ",
    "                                                             ]```]             ]`````````````````#````J``````]         ]CCCCCC``BBB]    ",
    "                                                             ]```]             ]`````````````````#```````````]         ]CCCCCC`````]    ",
    "                                                             ]```]             ]`````````````````#ïïïïïïïïïï#]         ]CCCCCC`````]    ",
    "                                                             ]```]]]]]]]]]]]]] ]`````````````````````````````]         ]CCCCCC`````]    ",
    "                                                             ]```]```````````] ]`````````````````````````````]         ]k;Y;```````]    ",
    "                                                             ]```+`;;`;``````] ]``````ĉ``````````````````````]         ]`;`;```````]    ",
    "                                                             ]```];;;;;Y```Y`] ]`````````````````````````````]         ]`;`;```````]    ",
    "                                                             ]```];``Y;```;;n] ]````````#````````````````````]         ]`;;;`c`````]    ",
    "                                                             ]```];;;;;``;;;k] ]`````````````````````````````]         ]]]]]]]]]]]]]    ",
    "                                                             ]```];Y;;;;;;;;;] ]`````````````````````````````]                          ",
    "                                                             ]```];`;;;;;;Y;;] ]`````````````````````````````]                          ",
    "                                                             ]```]``;;;;;;;;;] ]`````````````````````````````]                          ",
    "                                                             ]```]]]]]]]]]]]]] ]`````````````````````````````]                          ",
    "                                                             ]```]             ]`````````````````````````````]                          ",
    "                                                             ]```]             ]`````````````````````````````]                          ",
    "                                                             ]```]             ]`````````````````````````````]]]]]]]]]]]]]]]]]]]        ",
    "                                                             ]```]             ]`````````````````````````````+`````````````````]        ",
    "                                                             ]```]]]]]]]]]]]]]]]`````````````````````````````+`````````````````]        ",
    "                                                             ]`````````````````+`````````````````````````````+`````````````````]        ",
    "                                                             ]`````````````````+`````````````````````````````]]]]]]]]]]]]]]]```]        ",
    "                                                             ]```]]]]]]]]]]]]]]]`````````````````````````````]             ]```]        ",
    "                                                             ]```]             ]`````````````````````````````]             ]```]        ",
    "                                                             ]```]             ]`J```J```J```J```J```J```J```]             ]```]        ",
    "                                                             ]```]             ]`````````````````````````````]             ]```]        ",
    "                                                             ]```]             ]`J```J```J```J```J```J```J```]             ]```]        ",
    "                                                             ]```]             ]`````````````````````````````]             ]```]        ",
    "                                                             ]```]             ]`J```J```J```J```J```J```J```]             ]```]        ",
    "                                                             ]```]             ]`````````````````````````````]             ]```]        ",
    "                                                             ]```]             ]`J```J```J```J```J```J```J```]             ]```]        ",
    "                                                             ]```]             ]`````````````````````````````]             ]```]        ",
    "                                                             ]```]             ]`````````````````````````````]             ]```]        ",
    "                                                             ]```]             ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]             ]```]        ",
    "                                                             ]```]                                                         ]```]        ",
    "                                                             ]```]                                                         ]```]        ",
    "                                                             ]```]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]```]        ",
    "                                                             ]`````````````````````````````````````````````````````````````````]        ",
    "                                                             ]`````````````````````````````````````````````````````````````````]        ",
    "                                                             ]`````````````````````````````````````````````````````````````````]        ",
    "                                                             ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]`````````]]]]]]]]]]]]]]]]]]]]]]]]]]        ",
    "                                                                                            ]`````````]                                 ",
    "                                                                                            ]`````````]                                 ",
    "                                                                                            ]`````````]                                 ",
    "                                                                                            ]`````````]                                 ",
    "                                                                                            ]`````````]                                 ",
    "                                                                                            ]`````````]                                 ",
    "                                                                                            ]]]#%%%#]]]                                 ",
    "                                                                                               #...#                                    ",
    "                                                                                               #b..#                                    ",
    "                                                                                               #####                                    "
  ]
});
