/* ISOLATION map — edit by hand, or open editor.html and load this file.
   Placeholder. Nothing is drawn here yet beyond four walls and a spawn. */
ISO.register({
  "id": "CommandMidTower",
  "name": "COMMAND MID-TOWER // DON'T DO IT FOR THE WOMEN",
  "w": 100,
  "h": 101,
  "spawn": {"x": 1, "y": 2},
  "beacons": [],
  "dark": true,
  "din": true,
  "props": {
    "42,1": {"armed":true,"label":"","circuit":""},
    "47,1": {"reach":6,"label":"","circuit":""},
    "76,1": {"title":"COMMAND CONSOLE","text":"No readable record.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "77,1": {"dest":"CommandPlateau","arrive":"","fade":false,"card":"","cardsub":"","label":"","circuit":""},
    "42,2": {"armed":true,"label":"","circuit":""},
    "5,3": {"title":"Note from Patrica","text":"For those who come after me, there's something on this floor.\n\nI haven't seen it with my own eyes, it's much too dark for that, but I know it's here.\n\nIt can't see me either. Only here. I've had to hide in lockers from it, but have never been able to see it while I do.\n\nMy schematics say there is a secure elevator leading to the Plateau on the other side of the floor. It's locked down because of the power, but there are generators to get it up and running.\n\nBrought my own fuel, didn't use all of it, stashed it in the break room.\n\n- PATRICA"},
    "42,3": {"armed":true,"label":"","circuit":""},
    "8,4": {"ability":"flashlight","label":"","circuit":""},
    "42,4": {"armed":true,"label":"","circuit":""},
    "8,5": {"ability":"motion","label":"","circuit":""},
    "22,5": {"label":""},
    "23,5": {"dir":"right","label":""},
    "42,5": {"armed":true,"label":"","circuit":""},
    "40,6": {"dir":"right"},
    "42,6": {"armed":true,"label":"","circuit":""},
    "18,7": {"dir":"right"},
    "42,7": {"armed":true,"label":"","circuit":""},
    "18,8": {"dir":"right"},
    "22,8": {"dir":"right"},
    "41,8": {"title":"COMMAND CONSOLE","text":"No readable record.","desktop":true,"files":[{"kind":"doc","name":"Relocating the Elevator Lock Controls","folder":"","pass":"","targets":[],"text":"In accordance with recent safety measures passed by SAFFRON after the security incident aboard the USSN Polaris, the Elevator Lock controls have be relocated to Officer Low's room. Since he is on the Night Shift, he will not be here to decorate until after the launch of the ship."},{"kind":"app","name":"ELEVATOR LOCKS","folder":"","pass":"","targets":[{"x":74,"y":18},{"x":75,"y":18}],"text":""}],"card":"","cardsub":"","circuit":"ELEVATORLOCK"},
    "42,8": {"armed":true,"label":"","circuit":""},
    "8,11": {"label":""},
    "75,12": {"title":"Note from Patrica 3","text":"Made it to the elevator.\nHeading up to Plateau now. Going to try and find Command and figure out what they're doing to fix this"},
    "76,12": {"targets":[{"x":77,"y":12}],"label":"","circuit":"ELEVATORLOCK"},
    "77,12": {"dir":"up","dist":7,"circuit":""},
    "15,13": {"open":false,"locked":false,"circuit":""},
    "8,14": {"label":""},
    "27,14": {"dir":"right","label":""},
    "8,15": {"dir":"down"},
    "17,15": {"dir":"right","label":""},
    "22,15": {"dir":"right","label":""},
    "27,16": {"dir":"right","label":""},
    "17,17": {"dir":"right","label":""},
    "22,17": {"dir":"right","label":""},
    "74,18": {"open":false,"circuit":"ELEVATORLOCK"},
    "75,18": {"open":false,"circuit":"ELEVATORLOCK"},
    "17,19": {"dir":"right","label":""},
    "22,19": {"dir":"right","label":""},
    "17,21": {"dir":"right","label":""},
    "22,21": {"dir":"right","label":""},
    "32,21": {"dir":"right","range":3,"armed":true,"objective":"","label":"","circuit":""},
    "35,23": {"targets":[{"x":5,"y":29}],"label":"","circuit":""},
    "92,23": {"dir":"right"},
    "98,23": {"title":"COMMAND CONSOLE","text":"No readable record.","desktop":true,"files":[{"kind":"app","name":"LASER CONTROLS","folder":"","pass":"","targets":[{"x":87,"y":57}],"text":""}],"card":"","cardsub":"","circuit":""},
    "53,24": {"dir":"down","label":""},
    "96,25": {"dir":"right"},
    "92,27": {"dir":"right"},
    "97,27": {"dir":"right"},
    "5,29": {"dir":"right","open":false,"locked":false,"circuit":""},
    "6,29": {"dir":"right","open":false,"locked":false,"circuit":""},
    "7,29": {"dir":"right","open":false,"locked":false,"circuit":""},
    "8,29": {"dir":"right","open":false,"locked":false,"circuit":""},
    "41,29": {"dir":"right","label":""},
    "92,29": {"label":""},
    "93,29": {"label":""},
    "96,29": {"dir":"right"},
    "98,31": {"rating":"a15","label":""},
    "51,32": {"reach":6,"label":"","circuit":""},
    "92,32": {"dir":"right"},
    "96,32": {"label":""},
    "97,32": {"label":""},
    "98,32": {"label":""},
    "8,33": {"dir":"right"},
    "97,33": {"dir":"right"},
    "92,34": {"label":""},
    "93,34": {"label":""},
    "8,35": {"label":""},
    "92,35": {"label":""},
    "93,35": {"label":""},
    "96,35": {"label":""},
    "97,35": {"label":""},
    "98,35": {"label":""},
    "8,36": {"label":""},
    "92,36": {"label":""},
    "93,36": {"label":""},
    "96,36": {"dir":"right"},
    "98,36": {"label":""},
    "8,37": {"label":""},
    "56,37": {"dir":"down"},
    "92,37": {"label":""},
    "93,37": {"label":""},
    "98,37": {"label":""},
    "8,38": {"dir":"right"},
    "92,38": {"dir":"right"},
    "96,38": {"label":""},
    "97,38": {"label":""},
    "98,38": {"label":""},
    "98,39": {"label":"","circuit":""},
    "37,40": {"reach":6,"label":"","circuit":""},
    "56,40": {"opens":"barn","label":""},
    "98,40": {"label":"","circuit":""},
    "98,41": {"label":"","circuit":""},
    "76,42": {"dir":"right","label":""},
    "98,42": {"label":"","circuit":""},
    "98,43": {"label":"","circuit":""},
    "15,44": {"label":""},
    "23,44": {"label":""},
    "15,45": {"label":""},
    "16,45": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":true,"files":[{"kind":"doc","name":"Stupid Fucking Lasers","folder":"","pass":"","targets":[],"text":"I'm shutting down Mid-Way for the night yesterday and these damn laser trip-wires keep going off, even when I'm not near them. And they're sooooo loud!\n\nThen the damn Commander comes on down and tears me a new one for setting it off! It's not my fucking fault they're faulty. Even then, I can't turn them off, I don't know the code, and the terminal controlling it is all the way by the elevator! All I can control is the damn elevator doors.\n"},{"kind":"doc","name":"Panopticon Welcoming Message","folder":"Security Measures","pass":"","targets":[],"text":"Congratulations on your successful install of Panopticon Security Measures products, such as the following:\n\nLASER ALARMS\nSECURITY DRONES\nSECURITY TURRETS\nSPECTRES"}],"card":"","cardsub":"","circuit":""},
    "23,45": {"label":""},
    "15,46": {"label":""},
    "16,46": {"label":""},
    "17,46": {"label":""},
    "18,46": {"label":""},
    "19,46": {"label":""},
    "20,46": {"label":""},
    "21,46": {"label":""},
    "22,46": {"label":""},
    "23,46": {"label":""},
    "37,48": {"dir":"down","label":""},
    "55,49": {"dir":"left"},
    "74,49": {"label":"","circuit":""},
    "75,49": {"label":"","circuit":""},
    "76,49": {"label":"","circuit":""},
    "90,50": {"hears":26,"range":0,"label":""},
    "66,51": {"title":"BROADCAST","text":"Colour bars. Nothing behind them.","label":"","circuit":""},
    "70,51": {"dir":"right"},
    "66,52": {"title":"BROADCAST","text":"Colour bars. Nothing behind them.","label":"","circuit":""},
    "85,52": {"label":""},
    "58,53": {"dir":"down"},
    "66,53": {"title":"BROADCAST","text":"Colour bars. Nothing behind them.","label":"","circuit":""},
    "69,53": {"label":""},
    "70,53": {"dir":"right"},
    "85,53": {"label":""},
    "40,54": {"label":""},
    "48,54": {"label":""},
    "66,54": {"title":"BROADCAST","text":"Colour bars. Nothing behind them.","label":"","circuit":""},
    "85,54": {"label":""},
    "44,56": {"label":"","circuit":""},
    "45,56": {"label":"","circuit":""},
    "46,56": {"label":"","circuit":""},
    "55,56": {"title":"Mid-Way Lost","text":"Command is having us retreat back up into the plateau. Damnit! \n\nWe just got up here from the dome, and those damn things got a ride up the elevator. We set the hallway leading to it on fire, but they are making their way through.\n\nI don't know what they're going to do once we get up there. There's no where to go.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "66,56": {"label":""},
    "67,56": {"label":""},
    "68,56": {"label":""},
    "69,56": {"label":""},
    "70,56": {"label":""},
    "70,57": {"label":""},
    "87,57": {"armed":true,"label":"","circuit":""},
    "88,57": {"armed":true,"label":"","circuit":""},
    "89,57": {"armed":true,"label":"","circuit":""},
    "90,57": {"armed":true,"label":"","circuit":""},
    "91,57": {"armed":true,"label":"","circuit":""},
    "92,57": {"armed":true,"label":"","circuit":""},
    "93,57": {"armed":true,"label":"","circuit":""},
    "94,57": {"armed":true,"label":"","circuit":""},
    "46,63": {"dir":"right","supply":"MID-WAY-FUSE","run":false,"label":""},
    "53,63": {"dir":"right","supply":"","run":false,"label":""},
    "60,63": {"dir":"right","supply":"","run":false,"label":""},
    "47,66": {"title":"GENERATOR 1 STATUS","text":"No readable record.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "51,66": {"title":"Note from Patrica 2","text":"I had to put a makeshift fuse into the fusebox. One... Rick made.\n\nThe real one probably got taken by the retreating command. Or... the dead command. Probably on a body down here somewhere\n"},
    "54,66": {"title":"UNLABELLED CONSOLE","text":"NON-FUNCTIONAL. STRIPPED FOR PARTS","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "61,66": {"title":"GENERATOR 3 STATUS","text":"SEVERELY DAMAGED.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "69,67": {"dir":"left","ways":[{"circuit":"ELEVATORLOCK","rating":"a15"}],"supply":"MID-WAY-FUSE","label":""},
    "37,70": {"label":""},
    "60,70": {"dir":"right"},
    "37,71": {"label":""},
    "37,72": {"label":""},
    "60,72": {"dir":"right"},
    "48,73": {"label":""},
    "49,73": {"dir":"right","label":""},
    "53,73": {"label":""},
    "54,73": {"label":""},
    "55,73": {"label":""},
    "56,73": {"label":""},
    "57,73": {"label":""},
    "87,73": {"dir":"up","label":""},
    "18,74": {"armed":true,"label":"","circuit":""},
    "19,74": {"armed":true,"label":"","circuit":""},
    "20,74": {"armed":true,"label":"","circuit":""},
    "45,74": {"opens":"barn","label":""},
    "69,74": {"opens":"barn","label":""},
    "17,75": {"label":""},
    "21,75": {"label":""},
    "23,75": {"dir":"right","label":""},
    "43,75": {"label":""},
    "77,75": {"dir":"right","label":""},
    "17,78": {"label":""},
    "21,78": {"label":""},
    "20,79": {"dir":"down","label":""}
  },
  "rows": [
    "    #########################]]]]]]]]]]]]]]]]]]]]   ]```]   ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]      ",
    "#####````.............CCCC..//````````````3``11$]   ]```]   ]``````````#````I[`````#`````````]      ",
    "#...+````.............CCCC..#]````````````3``111]   ]```]   ]``````````#```````````#`````````]      ",
    "#####n```######.......CCCC..#]````````````3``111]   ]```]   ]``````````#```````````#`````````]      ",
    "    #```M#    #.......CCCC..#]````````````3`````]   ]```]   ]``````````#```````````#`````````]      ",
    "    #```M#    #.......{}....#]````````````3`````]   ]```]   ]``````````######+######`````````]      ",
    "    #````#    #.............#]``````````t`3`````]]]]]```]   ]````````````````````````````````]      ",
    "    #````#    #...D.......AA#]````````````3`````]```````]   ]vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv]      ",
    "    #````#    #...D...D...LB#]```````````I3``AAB+```````]   ]vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv]      ",
    "    #````#    ###############]]]]]]]]]]]]]]]]]]]]]]]]```]   ]vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv]      ",
    "    #````#                                          ]```]   ]vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv]      ",
    "    #```5################################           ]```]   ]vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv]      ",
    "    #````......ď........................#           ]```]   ]``````````````nbT```````````````]      ",
    "    #````......-........................#           ]```]   ]````````````````````````````````]      ",
    "    #```5#######...........J............#           ]```]   ]````````````````````````````````]      ",
    "    #```ś#     #.J....J.................#           ]```]   ]````````````````````````````````]      ",
    "    #`ðð`#     #...........J......(..(..#           ]```]   ]````````````````````````````````]      ",
    "    #`ðð`#     #.J....J.........(((..(((#           ]```]   ]````````````````````````````````]      ",
    "    #`ðð`#     #..........######........#           ]```]   ]]]]]]]]]]]]]]%%]]]]]]]]]]]]]]]]]]      ",
    "    #````#     #.J....J...#    #........#           ]```]                ]``]                       ",
    "    #````#     #..........#    #........#           ]```]                ]``]                       ",
    "    #````#     #.J....J...#    #l.......#           ]```]                ]``]                       ",
    "    #```ŵ#     #..........#    #........#           ]```]                ]``]              ]]]]]]]]]",
    "    #```ŵ#     #..........#    #...b....#           ]```]                ]``]              ]t`````I]",
    "    #````#     ############    ##########           ]}``]                ]``]              ]```````]",
    "    #````#                                          ]```]                ]``]              ]````t``]",
    "    #````#                                          ]```]                ]``]              ]```````]",
    "    #````#                          ]]]]]]]]]]]]]]]]]```]                ]``]              ]t````t`]",
    "    #````#                          ]```````````````````]                ]``]              ]```````]",
    "    #>>>>#                          ]````}``````````````]                ]``]              ]88``t``]",
    "    ]````]                          ]````]]]]]]]]]]]]]]]]                ]``]              ]```````]",
    "    ]````]                          ]````]  ]]]]]]]]]]]]]]               ]``]              ]``````f]",
    "    ]ŵ```]                          ]````]  ]````11$11```]               ]``]              ]t```888]",
    "    ]ŵ``6]                          ]````]  ]````11111```]               ]``]              ]`````t`]",
    "    ]````]                          ]````]  ]````````````]               ]``]              ]88`````]",
    "    ]```8]                          ]````]  ]````````````]               ]``]              ]88``555]",
    "    ]```8]                          ]````]  ]``````````ðð]               ]``]              ]88``t`5]",
    "    ]```8]                          ]````]  ]````````ððvY]               ]``]              ]88````5]",
    "    ]```6]                          ]````]  ]```````ðð```]               ]``]              ]t```555]",
    "    ]````]                          ]11``]  ]``````ðð````]               ]``]              ]``````9]",
    "    ]````]                          ]$1``]  ]``````ð````k]               ]``]              ]``````9]",
    "    ]````]]]]]]]]]]]]]]]]]]]]]]]]]]]]11``]]]]+]]]]]]]]]]]]]]]]]]]]]]]]]]]]``]]]]]]]]]]]]]]]]``````9]",
    "    ]````(`````````````````+````````````````````````````````````````````````}``````````````+``````9]",
    "    ]````(`````````````````ď``````````````````'````````````````````````````````````````````+``````9]",
    "    ]````(`````)```````)```]]]]]]]]]]````]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]",
    "    ](((```````)c``````)```]        ]````]                                                          ",
    "    ]``````````)))))))))''`]        ]````]                                                          ",
    "    ]```łłł`````````````'``]        ]````]]]]]]]]]]]]]]]]]]]]                                       ",
    "    ]]]]]]]]``````````'''``]        ]}```+````((((``;;;;2222]    ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    ",
    "           ]`````````'`````]        ]```ł]``````````;;`Y2222]    ]````````999`````````+````````]    ",
    "           ]```'```````````]        ]```ł]```(``````;;;;2222]    ]`````````````ððð````]```4````]    ",
    "           ]```''``````````]        ]``łł]```(`````````;2222]    ]m```6```````ððððð```]````````]    ",
    "           ]````''`````````]        ]``ł`]```(`````````;;222]    ]m``````````ðððððð``{]````````]    ",
    "           ]`````''````````]        ]````]`(((``````````;;Y2]    ]m``ƒ6``````ðððððð``{]````````]    ",
    "           ]`'````''````'``]        ]```{]((````{````````;`;]    ]m``````````ððððð```{]````````]    ",
    "           ]`''````'``'''``]        ]`''`]``````CCCCCC```;`;]    ]```````łłł`ðððð`````]````````]    ",
    "           ]``''`````''````]        ]````]``999`CCCCCC`I`;;;]    ])))))```````````````]````````]    ",
    "           ]```''`'``'`````]        ]`łłł]]]]]]]]]]]]]]]]]]]]    ]````)```````````````]33333333]    ",
    "           ]```''''````````]        ]````]                       ]``````````ŵ``ŵ``ŵ```]````````]    ",
    "           ]```'```````````]        ]````]                       ]]]]]]]]]]]]]]]]]]]]]]''``````]    ",
    "           ]]]]]]]+ď+]]]]]]]        ]````]                                            ]'''`````]    ",
    "                 ]```]              ]````]  ]]]]]]]]]]]]]]]]]]]]]]]]]]]               ]'''`````]    ",
    "                 ]```]              ]ŵ```]  ]BBBBBBBBBBBBBBBBBBBBBB```]               ]''''````]    ",
    "                 ]```]              ]ŵ```]  ]Bĝ`````Bĝ`````Bĝ`````B```]               ]''''````]    ",
    "                 ]```]              ]ŵ```]  ]B``````B``````B``````B```]               ]`'''````]    ",
    "                 ]```]              ]ŵ```]  ]B``````B``````B``````B```]               ]`''''```]    ",
    "                 ]```]              ]ŵ`ł`]  ]B`c```nBBcBBBBBBcBBBBB```]               ]``'''```]    ",
    "                 ]```]              ]ŵ`ł`]  ]````````````````````````ü]               ]```''```]    ",
    "                 ]```]              ]``ł`]  ]`````````````````````````]               ]```````']    ",
    "                 ]```]              ]``ł`]  ]`````````````````````````]               ]``````'']    ",
    "                 ]```]              ]{`ł`]  ]``````````````at`a```````]               ]``````'']    ",
    "                 ]```]              ]{```]  ]``````````````a``a```````]               ]``````'']    ",
    "                 ]```]              ]{```]  ]```````````````t`````````]               ]`````''']    ",
    "                 ]```]              ]````]  ]```5}```88888`a``a```````]               ]}```'''']    ",
    "]]]]]]]]]]]]]]]]]]333]]]]]]]]]]]]]]]]`ďďď]]]]K]]]]]]]]]]]]]]]]]]]]]]]K]]]]]]]]]]]]]]]]]````'''']    ",
    "22222222222222```<```<`}```````````````````{`````````````````````````````````}````````````'''``]    ",
    "2222222222222222``````````````````````````````````````````````````````````````````````````'''``]    ",
    "2222222222222222``````````````````````````````````````````````````````````````````````````''```]    ",
    "2222222222222222`<```<`````````````````````````````````````````````````````````````````````````]    ",
    "]]]]]]]]]]]]]]]]]]``}]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    ",
    "                 ]```]                                                                              ",
    "                 ]```]                                                                              ",
    "                 ]```]                                                                              ",
    "                 ]``2]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              ",
    "                 ]222]                                                                              "
  ]
});
