/* ISOLATION map — edit by hand, or open editor.html and load this file. */
ISO.register({
  "id": "ENG-COMMAND",
  "name": "ENGINEERING COMMAND",
  "w": 54,
  "h": 59,
  "spawn": {"x": 27, "y": 58},
  "beacons": [],
  "props": {
    "25,2": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":false},
    "27,5": {"open":false},
    "27,6": {"open":false},
    "27,7": {"open":false},
    "46,8": {"targets":[],"label":""},
    "13,16": {"targets":[],"label":""},
    "46,21": {"dir":"up","dist":9},
    "16,33": {"dir":"right"},
    "20,33": {"dir":"right"},
    "36,33": {"dir":"right"},
    "16,35": {"dir":"right"},
    "20,35": {"dir":"right"},
    "32,35": {"dir":"right"},
    "36,35": {"dir":"right"},
    "16,37": {"dir":"right"},
    "20,37": {"dir":"right"},
    "32,37": {"dir":"right"},
    "36,37": {"dir":"right"},
    "16,39": {"dir":"right"},
    "20,39": {"dir":"right"},
    "32,39": {"dir":"right"},
    "36,39": {"dir":"right"},
    "16,41": {"dir":"right"},
    "20,41": {"dir":"right"},
    "32,41": {"dir":"right"},
    "36,41": {"dir":"right"},
    "16,43": {"dir":"right"},
    "20,43": {"dir":"right"},
    "32,43": {"dir":"right"},
    "36,43": {"dir":"right"},
    "16,45": {"dir":"right"},
    "20,45": {"dir":"right"},
    "32,45": {"dir":"right"},
    "36,45": {"dir":"right"},
    "27,58": {"dest":"","arrive":"","label":""}
  },
  "rows": [
    "             ############.....#############           ",
    "             ############.....#############           ",
    "             ############c....#############           ",
    "             ############.....#############           ",
    "             ############.....#############           ",
    "             ##############%###############           ",
    "             ##############%###############           ",
    "   ########################%#######################   ",
    "vvv#......CCCCCCCCC..................vvv......b.vv#   ",
    "vvv#..C.C....CCCCCCCB................vvv........vv#   ",
    "vvv#.............CCCBB...............vvvv.vv....vv#   ",
    "vvv#..C.C............BB.....A.A......vvvvvvvv...vv#   ",
    "vvv#..C....C..C.......BB....A.A......vvvvvvvvv.vvv#   ",
    "vvv#.........v..........B...AAA.A.....vvvvvvvvvvvv/   ",
    "vvv#...B..B.vvv..........B.....A......vvvvvvvvvvvv/   ",
    "vvv#.B..B..vvvvv..............A......vvvvvvvvvvvvv/   ",
    "vvv#......vv.bvvv......L............vvvvvvvvvvvvvv/   ",
    "vvv#.....vvv.ovvvv..................vvvvvvvvvvvvvv/   ",
    "vvv#....vvvv.vvvvvv..L...............vvvvvvvvvvvv./   ",
    "vvv#.....vvv.vvvvv....................vvvvvvvvvv../   ",
    "vvv#......vv.vvvv......................vvvvvvvv.../   ",
    "vvv#.......vvvvv...L....................vvvvvvT...#   ",
    "vvv#........vvv..........................vvvv.....#   ",
    "vvv#.........v...L........................vv......#   ",
    "vvv#..............................................#   ",
    "vvv#..............................................#   ",
    "vvv#..................v...........................#   ",
    "vvv#.................vvv..........................#   ",
    "vvv#................vvvvv.v..v....................#   ",
    "vvv#...............vvvvvvv..vv....................#   ",
    "vvv#................vvvvv....v....................#   ",
    "vvv#.................vvv..........................#   ",
    "vvv#..................v...........................#vvv",
    "vvv#............D...D...........B...D.............#vvv",
    "vvv#..............................................#vvv",
    "vvv#............D...D...........D...D.............#vvv",
    "vvvv#L...........................................L#vvv",
    "vvvv#L..........D...D...........D...D............L#vvv",
    "vvvvv#L.........................................L#vvvv",
    "vvvvv#L.........D...D...........D...D...........L#vvvv",
    "vvvvvv#.........................................#vvvvv",
    "vvvvvv#CCC......D...D...........D...D........CCC#vvvvv",
    "vvvvvv#CCC...................................CCC#vvvvv",
    "vvvvvv#CCC......D...D...........D...D........CCC#vvvvv",
    "vvvvvvv####.................................####vvvvvv",
    "vvvvvvvvvvv##...D...D...........D...D.....##vvvvvvvvvv",
    "vvvvvvvvvvvvv##.........................##vvvvvvvvvvvv",
    "vvvvvvvvvvvvvvv##########.....##########vvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvv##+##vvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvx.xvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvx.xvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvx.xvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvx.xvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvx.xvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvx.xvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvx.xvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvx.xvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#^#vvvvvvvvvvvvvvvvvvvvvvvvv"
  ]
});
