/* ISOLATION map — edit by hand, or open editor.html and load this file. */
ISO.register({
  "id": "ENG-COMMAND",
  "name": "ENGINEERING COMMAND",
  "w": 61,
  "h": 133,
  "spawn": {"x": 29, "y": 132},
  "beacons": [],
  "props": {
    "29,15": {"dir":"right"},
    "16,16": {"dest":null,"label":""},
    "26,20": {"dir":"right"},
    "33,20": {"dir":"right"},
    "15,21": {"dir":"right"},
    "30,21": {"dir":"right"},
    "22,23": {"dir":"right"},
    "34,23": {"dir":"right"},
    "42,23": {"dir":"right"},
    "12,24": {"dir":"right"},
    "29,24": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":false,"circuit":""},
    "28,25": {"dir":"right"},
    "12,26": {"dir":"right"},
    "18,26": {"dir":"right"},
    "29,26": {"dir":"right"},
    "44,26": {"dir":"right"},
    "35,27": {"dir":"right"},
    "37,27": {"dir":"right"},
    "46,27": {"rating":"a15","label":""},
    "12,28": {"dir":"right"},
    "46,28": {"dir":"right"},
    "22,29": {"dir":"right"},
    "40,29": {"dir":"right"},
    "47,29": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":false,"circuit":""},
    "12,30": {"dir":"right"},
    "15,30": {"dir":"right"},
    "20,30": {"dir":"right"},
    "16,31": {"targets":[],"label":"","circuit":""},
    "17,31": {"dir":"down"},
    "8,42": {"ways":[{"circuit":"BUTTON","rating":"a15"}],"label":""},
    "11,42": {"dest":{"x":38,"y":85},"label":""},
    "8,44": {"targets":[],"label":"","circuit":""},
    "8,45": {"dir":"down","dist":26,"circuit":""},
    "11,45": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":false,"circuit":""},
    "32,54": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":false,"circuit":""},
    "30,55": {"open":false,"circuit":""},
    "30,71": {"dir":"up","dist":17,"circuit":""},
    "31,71": {"targets":[{"x":30,"y":71},{"x":30,"y":55}],"label":"","circuit":"BUTTON"},
    "45,71": {"dir":"right"},
    "29,72": {"dir":"right"},
    "32,72": {"dir":"down"},
    "46,72": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":false,"circuit":""},
    "17,73": {"dir":"down"},
    "18,73": {"dir":"right"},
    "23,73": {"dir":"right"},
    "28,73": {"dir":"down"},
    "7,74": {"targets":[],"label":"","circuit":""},
    "18,74": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":false,"circuit":""},
    "35,74": {"dir":"right"},
    "35,77": {"dir":"right"},
    "35,80": {"dir":"right"},
    "35,83": {"dir":"right"},
    "35,85": {"dir":"right"},
    "38,85": {"dest":null,"label":""},
    "30,86": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":false,"circuit":""},
    "32,87": {"dest":{"x":16,"y":16},"label":""},
    "28,116": {"targets":[{"x":29,"y":116}],"label":"","circuit":""},
    "29,116": {"dir":"up","dist":29,"circuit":""},
    "29,132": {"dest":"ENGLVL2","arrive":"","label":"ENGINEERING COMMAND ELEVATOR","circuit":""}
  },
  "rows": [
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvv###########################vvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvv##..CCALLALLLAD..CALLLLLLACCC##vvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvv##AV,.CC...........C........CCC..##vvvvvvvvvvvvv",
    "vvvvvvvvvvv##BB,,,..............................##vvvvvvvvvvv",
    "vvvvvvvvv##BB.....................................##vvvvvvvvv",
    "vvvvvvvv#BB...................,,.BB.................#vvvvvvvv",
    "vvvvvvvv#BB...,,,.........D...,BBD..................#vvvvvvvv",
    "vvvvvvv#......,D........,,...,D......................#vvvvvvv",
    "vvvvvvv#......,.........,B,..........................#vvvvvvv",
    "vvvvvv#B.............BD..,.....,..D.......D...........#vvvvvv",
    "vvvvvv#B....D...B....B..B....c,B......................#vvvvvv",
    "vvvvv#..........B...........D.B,.......................#vvvvv",
    "vvvvv#......D....BD..........D..............D..........#vvvvv",
    "vvvv#.......=...........,....BB.BBBD.D.......Bf.........#vvvv",
    "vvvv#.......D..........AA,...................BD.........#vvvv",
    "vvv#..............,...D.................D......c.........#vvv",
    "vvv#.......=D..D...,D....................................#vvv",
    "vv#~.......=~~..bD..,.....................................#vv",
    "vv##//////#################################################vv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvv..vvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvv..vv..vvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvv..vvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvv..vvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv##vv##vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#u..V#vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#....#vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#b...#vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#T..c#vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#//###vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#####vvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvv#.....#vvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#.......#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#.......#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#.......#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#.......#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#.......#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvv#....c#vvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv##%##vvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vv#####vvvvv###vvvvv####vvvvvvvvvvvvvvvvvvvvv####vvv#######vv",
    "vv#.........BBB.....LLL.......Tb..L..........D............#vv",
    "vvv#.......AAAL..............D..DLL...........c..........#vvv",
    "vvv#.....AAAAAL..DD..B.D....D............................#vvv",
    "vvvv#..bAAAAA.....c...BB...........D....................#vvvv",
    "vvvv#AAAAA........B....BB...............................#vvvv",
    "vvvvv#AAA........BB....................................#vvvvv",
    "vvvvv#.............................D...................#vvvvv",
    "vvvvvv#.........=......~,,...........~................#vvvvvv",
    "vvvvvv#.........=.......~,,.........~.................#vvvvvv",
    "vvvvvvv#..................,~.......D.................#vvvvvvv",
    "vvvvvvv#..................,~~........................#vvvvvvv",
    "vvvvvvvv##.......=.........,.......................##vvvvvvvv",
    "vvvvvvvvvv##.......................D.............##vvvvvvvvvv",
    "vvvvvvvvvvvv##....................,,...........##vvvvvvvvvvvv",
    "vvvvvvvvvvvvvv##............#####.,D..V......##vvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvv##############c##############vvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#...V#vvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.####vvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#xxxxxxxbT.xxxxxxx#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#.................#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#.................#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#.................#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#.................#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#.................#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#.................#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#.................#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#########.#########vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#^#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
  ]
});
