/* ISOLATION map — edit by hand, or open editor.html and load this file. */
ISO.register({
  "id": "EngCom",
  "name": "EngineeringCommand",
  "w": 61,
  "h": 133,
  "spawn": {"x": 29, "y": 132},
  "beacons": [],
  "props": {
    "29,15": {"dir":"right"},
    "16,16": {"dest":{"x":32,"y":87},"label":""},
    "35,16": {"dir":"right"},
    "26,20": {"dir":"right"},
    "33,20": {"dir":"right"},
    "11,21": {"dir":"right"},
    "15,21": {"dir":"right"},
    "30,21": {"dir":"right"},
    "19,22": {"dir":"down"},
    "22,23": {"dir":"right"},
    "34,23": {"dir":"right"},
    "42,23": {"dir":"right"},
    "12,24": {"dir":"right"},
    "28,24": {"dir":"down"},
    "29,24": {"title":"Pre-Launch Concerns about \"Exo-Invasionablity\" ","text":"TO: Lunar Senator Jonah Hale\nFROM: L.S.V MARE PUBLIC RELATIONS TEAM\nTOPIC: Concern Emails\n------------\nSorry to disturb you during such a crucial moment in your campaign but we've been fielded one too many emails from concerned patrons within your district about the possibility of alien invasion of the Mare while on it's way to 61 Cygni.\n\nIf you could kindly hold a press conference to calm these people down, it would be great.","desktop":false,"circuit":""},
    "12,26": {"dir":"right"},
    "18,26": {"dir":"right"},
    "29,26": {"dir":"right"},
    "44,26": {"dir":"right"},
    "48,26": {"dir":"right"},
    "52,26": {"dir":"right"},
    "13,27": {"dir":"right"},
    "37,27": {"dir":"right"},
    "46,27": {"rating":"a15","label":""},
    "12,28": {"dir":"right"},
    "46,28": {"dir":"right"},
    "51,28": {"dir":"right"},
    "22,29": {"dir":"right"},
    "40,29": {"dir":"right"},
    "47,29": {"title":"Engineering Lunch Log","text":"[ P - Patrick\n  C - Carl\n  L - Louise\n  M - Martin ]\n\nC - I was down in Water Treatment, right? Nothing down there is maintained. There's leaks, burst pipes. Literally nothing is stable.\n\nM - Isn't that Nights' job?\n\nC - Evidently, they didn't do it!\n\nL - Have you seen anyone from Night yet?\n\nC - No, I assume they thought they could go back to cyro early. I'm too busy to run down and check on em.\n\nP - I have a buddy in Cyro, I'll have him check on them.\n\nC - Tell him to wake one of them up, and pucnh em!\n\n*Laughter*\n\nP.A SYSTEN - ANNOUNCMENT. EXTRA HANDS REQUIRED ON WATER TREATMENT REPAIR. LUNCH IS CANCELLED","desktop":false,"circuit":""},
    "12,30": {"dir":"right"},
    "15,30": {"dir":"right"},
    "20,30": {"dir":"right"},
    "54,30": {"dir":"right"},
    "17,31": {"dir":"down"},
    "50,31": {"dir":"right"},
    "8,42": {"ways":[{"circuit":"BUTTON","rating":"a15"}],"label":""},
    "8,44": {"targets":[{"x":8,"y":45}],"label":"","circuit":""},
    "8,45": {"dir":"down","dist":26,"circuit":""},
    "11,45": {"title":"Power Concerns","text":"I want to note this for the technician on the Day. The fuse for this fucking fusebox is gone, and don't know where it went.","desktop":false,"circuit":""},
    "29,50": {"dest":"WaterTreatmentTop","arrive":"","label":""},
    "29,53": {"dir":"right"},
    "32,54": {"title":"Piles and Piles of Tragedy","text":"A thousand of bodies laid asunder...\nSuch such...\nLogistical loss.\nDown into the water they go.\nSoon, everyone will know.\n- Cygnus","desktop":false,"circuit":""},
    "30,55": {"open":false,"circuit":""},
    "11,71": {"dest":{"x":38,"y":85},"label":""},
    "30,71": {"dir":"up","dist":17,"circuit":""},
    "31,71": {"targets":[{"x":30,"y":71}],"label":"","circuit":"BUTTON"},
    "45,71": {"dir":"right"},
    "16,72": {"dir":"right"},
    "29,72": {"dir":"right"},
    "32,72": {"dir":"down"},
    "47,72": {"title":"Water Treatment Anomalies","text":"TO: HEAD OF AGRI, HEAD OF BIO, HEAD Of MED.\nFROM: HEAD OF ENG\nTOPIC: ANOMALIES DETECTED IN WATER TREATMENT PLANT.\n---------\nI was going through the purity reports for when Night Shift was on duty. There is a... Well, I don't know how to put it, an anomaly, on the report. Something labelled UBC-1. I can't find anything in the handbook about it, and nothing seems to show up in the database. \n\nIf anyone finds out what UBC-1 is, please tell me! I don't want this ending up like L.S.V Dark.","desktop":false,"circuit":""},
    "17,73": {"dir":"down"},
    "18,73": {"dir":"right"},
    "23,73": {"dir":"right"},
    "28,73": {"dir":"down"},
    "7,74": {"targets":[{"x":30,"y":55}],"label":"","circuit":""},
    "18,74": {"title":"Bring Your Kid to Work Day","text":"BRING YOUR KID TO WORK DAY!!!\n-------------------------\nBy the command of the Head of Medical, since we are 25 years into the journey to 61 Cygni, all children below the age of 14 are required to come out of Cyrostasis for a period of 48 hours for a series of checkups. In order to boost morale, we will allow all crew to bring their related children to work for the initial 24 hours.\n\nThey will not be allowed to stay for the second.","desktop":false,"circuit":""},
    "35,74": {"dir":"right"},
    "13,75": {"dir":"right"},
    "30,76": {"dir":"down"},
    "35,77": {"dir":"right"},
    "8,78": {"dir":"right"},
    "12,80": {"dir":"up"},
    "35,80": {"dir":"right"},
    "44,80": {"dir":"up"},
    "33,81": {"dir":"right"},
    "35,83": {"dir":"right"},
    "44,83": {"dir":"right"},
    "35,85": {"dir":"right"},
    "38,85": {"dest":{"x":11,"y":71},"label":""},
    "44,85": {"title":"Last Words","text":"The note is stained in blood.\n\nThe only legible text reads:\n\nAmen."},
    "30,86": {"title":"Ventilation Survival Log 1","text":"This is-. \nFuck the introduction, I don't have time.\nThey got onboard a couple of hours ago. Started slaughtering the night crew, then moved onto us when we came back from cyro.\n\nThe ship is fucked, everything is down or going down because Night were dead and didn't repair.\n\nGotta find a way off.\n","desktop":false,"circuit":""},
    "32,87": {"dest":{"x":16,"y":16},"label":""},
    "28,116": {"targets":[{"x":29,"y":116}],"label":"","circuit":""},
    "29,116": {"dir":"up","dist":29,"circuit":""},
    "29,132": {"dest":"ENGLVL2","arrive":"","label":"","circuit":""}
  },
  "rows": [
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvv###########################vvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvv##..CCALLALLLAD..CALLLLLLACCC##vvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvv##AV,.CC...........C..Y.....CCC..##vvvvvvvvvvvvv",
    "vvvvvvvvvvv##BB,,,..............;;;;;;..........##vvvvvvvvvvv",
    "vvvvvvvvv##BB.................;;;;;;;;............##vvvvvvvvv",
    "vvvvvvvv#BB...................,,SBBS;;..............#vvvvvvvv",
    "vvvvvvvv#BB...,,,.........D...,BBD..................#vvvvvvvv",
    "vvvvvvv#...Y..,Y  ......,,;;;,D......................#vvvvvvv",
    "vvvvvvv#......,....Y....,BX;;........................#vvvvvvv",
    "vvvvvv#B.............BD..,;;;..,..D.......D........;..#vvvvvv",
    "vvvvvv#B....D...B....B..B...Yc,B...............;;;;;;;#vvvvvv",
    "vvvvv#..........B.............B,..........;;;;;;;;;;...#vvvvv",
    "vvvvv#......D....BD..........D............;;D...Y...Y..#vvvvv",
    "vvvv#.......=Y..........,....BB.BBB..D...;;..Bf.........#vvvv",
    "vvvv#.......D..........AA,.....;;;;;.....;;;.BD....Y....#vvvv",
    "vvv#..............,...D...;;;;;;;;;;....D..;...c.........#vvv",
    "vvv#.......=D..D...,D...;;;;;;;;;;;......;;;..........Y..#vvv",
    "vv#~.......=~~..vD..,...;;;;;;;;;;;......;;;......Y.......#vv",
    "vv##//////####### #########################################vv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvv..vvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvv..vv..vvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvv..vvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvv..vvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv##vv##vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#u...#vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#....#vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#b...#vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#T..c#vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvv#//###vvvvvvvvvvvvvvvv# #vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#####vvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;#vvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#;;;S;;;#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#;XO..X;#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#;X...X;#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#;X...X;#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvv#;;Y.;;;#vvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;c#vvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv##%##vvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#v#vvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvv#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vv#####vvvvv###vvvvv####vvvvvvvvvvvvvvvvvvvvv####vvv#######vv",
    "vv#........VBBB.....LLL.......Tb..L..........D............#vv",
    "vvv#.......AAAL.Y............D..DLL............c.........#vvv",
    "vvv#.....AAAAAL..DD..B.D....D.........;..................#vvv",
    "vvvv#..bAAAAA.....c...BB...........D...;;;.......;.;....#vvvv",
    "vvvv#AAAAA...Y....B....BB.................;;;;;;.;;.....#vvvv",
    "vvvvv#AAA........BB...;.......Y..............;;;;......#vvvvv",
    "vvvvv#..............X..;;;.........D....;;.;;.;........#vvvvv",
    "vvvvvv#.Y.......=..XX..~,,;;;;;;;;...~..;;;...........#vvvvvv",
    "vvvvvv#.........=..;.X..~,,.........~...;.............#vvvvvv",
    "vvvvvvv#....Y......;..XX..,~.......D........YLLLL....#vvvvvvv",
    "vvvvvvv#...........;...X..,~~....Y...........LAA.....#vvvvvvv",
    "vvvvvvvv##.......=..;;..X..,.................AAL...##vvvvvvvv",
    "vvvvvvvvvv##..........;.X;.........D......BBY..L.##vvvvvvvvvv",
    "vvvvvvvvvvvv##....................,,......BA;;;##vvvvvvvvvvvv",
    "vvvvvvvvvvvvvv##............#####.,D..V...BAn##vvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvv##############c##############vvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#...V#vvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.####vvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvxvvvxvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#xxxxxxxbT.xxxxxxx#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#.................#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#XX.............XX#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#XXX............XX#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#XXXX..........XXX#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#XXXXXX.......XXXX#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#XXXXXXX.....XXXXX#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#XXXXXXX.....XXXXX#vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvv#########.#########vvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#.#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvv#^#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
  ]
});
