/* ISOLATION map — edit by hand, or open editor.html and load this file. */
ISO.register({
  "id": "ENGLVL2",
  "name": "ENGINEERING LEVEL 2",
  "w": 54,
  "h": 27,
  "spawn": {"x": 53, "y": 14},
  "beacons": [{"x": 0, "y": 5}],
  "props": {
    "26,0": {"title":"Destinations","text":"Engineering Command","desktop":false},
    "28,0": {"dest":"ENG-COMMAND","arrive":"","label":"ENGINEERING COMMAND ELEVATOR"},
    "28,1": {"targets":[{"x":28,"y":0}],"label":""},
    "30,1": {"targets":[{"x":30,"y":10},{"x":31,"y":10},{"x":32,"y":10}],"label":""},
    "31,1": {"title":"Tram Concerns","text":"COMPLAINT SENT TO COMMAND: These trams are going to be the death of us! They can barely fit one person, and we're supposed to be moving at a pace that requires us to put three on one. They are hanging off the side!\n","desktop":false},
    "33,1": {"dir":"right"},
    "45,1": {"dir":"right"},
    "20,2": {"dir":"down"},
    "22,2": {"dir":"down"},
    "24,2": {"dir":"down"},
    "26,2": {"dir":"down"},
    "0,3": {"ability":"jump","label":"VAULT SERVOS"},
    "18,4": {"targets":[{"x":19,"y":5},{"x":19,"y":6}],"label":""},
    "51,4": {"dir":"right"},
    "19,5": {"open":false},
    "28,5": {"title":"Emergency Distress (Unsent)","text":"MAYDAY! MAYDAY! THIS IS THE LSV MARE. WE ARE UNDER ATTACK BY-.","desktop":false},
    "37,5": {"dir":"right"},
    "44,5": {"dir":"right"},
    "19,6": {"open":false},
    "20,7": {"dir":"down"},
    "22,7": {"dir":"down"},
    "24,7": {"dir":"down"},
    "26,7": {"dir":"down"},
    "37,7": {"dir":"right"},
    "31,8": {"targets":[{"x":31,"y":9}],"label":""},
    "31,9": {"dir":"down","dist":9},
    "37,9": {"dir":"right"},
    "1,10": {"dir":"down","dist":7},
    "30,10": {"open":false},
    "31,10": {"open":false},
    "32,10": {"open":false},
    "40,10": {"title":"ENGINEERING OFFICE LOG","text":"Travel Year 12\n-------------------------\nReactor Maintenance Underway; Tokamak Fusion Reactor noted to be decaying in terms of stability faster than expected. Possibly due to higher-than-average external radiation.\n\nATTACHED LOG:\n[L = Louise, M = Martin]\n\nL: \"It's bullshit, right?\" \n\nM: \"Can't be.\"\n\nL: \"These is Chernobyl level readings!\"\n\nM: \"It just is.\"\n\nL: \"No the fuck it isn't? Is Exo sure those sensors aren't broken?\"\n\nM: \"Yup.\"\n\nL: \"Well, either they're wrong, or there's something out there.\"\n\nM: \"So the former?\"\n\nL: \"Obviously.\"","desktop":false},
    "52,11": {"targets":[{"x":51,"y":12},{"x":51,"y":13},{"x":51,"y":14},{"x":51,"y":15}],"label":""},
    "51,12": {"open":false},
    "51,13": {"open":false},
    "51,14": {"open":false},
    "53,14": {"dest":"tutorial","arrive":"","label":"PRIMARY-ENG-ELEVATOR"},
    "51,15": {"open":false},
    "2,17": {"targets":[{"x":1,"y":10}],"label":""},
    "8,18": {"title":"Discovered Contraband","text":"Contraband Log:\n\n* 20 Assorted Containers of Unauthorized Substance\n* 7 Unregistered Androids\n* 2 Pounds of Mozzarella","desktop":false},
    "28,18": {"title":"Motion Detected at Cargo Bay 07 Entrance","text":"00:01; Camera Activated.\n\n00:04; Rumbling noise detected.\n\n00:10; Security Personnel Dispatched.\n\n00:20; Rumbling detected.\n\n00:40; Security Personnel arrives.\n\n00:45; SP: \"Security! Is someone down here?!\"\n\n00:50; Thump detected.\n\n00:55; Motion ceased.","desktop":false},
    "11,19": {"dir":"right"},
    "7,23": {"dir":"down"},
    "12,23": {"dir":"right"},
    "18,24": {"dir":"down"},
    "20,24": {"dir":"down"},
    "0,26": {"open":false,"locked":true},
    "1,26": {"open":false,"locked":true},
    "2,26": {"open":false,"locked":true},
    "3,26": {"open":false,"locked":true},
    "4,26": {"open":false,"locked":true},
    "5,26": {"open":false,"locked":true},
    "6,26": {"open":false,"locked":true},
    "7,26": {"open":false,"locked":true},
    "8,26": {"open":false,"locked":true},
    "9,26": {"open":false,"locked":true},
    "10,26": {"open":false,"locked":true},
    "11,26": {"open":false,"locked":true},
    "12,26": {"open":false,"locked":true},
    "13,26": {"open":false,"locked":true},
    "14,26": {"open":false,"locked":true},
    "15,26": {"open":false,"locked":true},
    "16,26": {"open":false,"locked":true},
    "17,26": {"open":false,"locked":true},
    "18,26": {"open":false,"locked":true},
    "19,26": {"open":false,"locked":true},
    "20,26": {"open":false,"locked":true},
    "21,26": {"open":false,"locked":true}
  },
  "rows": [
    ".....vv...vvv.=vv~~#......c.^###########L.............",
    ".....vv...vvv.=vvvv#........b#bc.D..AA.#L....D....BB..",
    ".....vv...vvv..,,vv#D.D.D.D..#.........#L.........BB..",
    "M....vv...vvv..vv,=#.........#........................",
    ".....vv...vvv.....b#.........#.........#...........D..",
    ".....vv...vvv......%........c#.......F.#..L.D.........",
    "o....vv...vvv......%.........#.........#.#######.#....",
    ".....vv...vvv.=,,vv#D.D.D.D..#.......F.#.#.......#....",
    ".....vv...vvv.=vvvv#.........#.b.......#.#.......#....",
    ".....vv...vvv.=vv~~#.........#.T.....F.#.#..!!!..#.LLL",
    ".T.###########################%%%#######c#..!!...#.###",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv####++########b#",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv,,...........%..",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv==...........%..",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv=,...........%.^",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv,,...........%..",
    "v.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv################",
    "..b###########################x.x#####             ###",
    "....LLLLc.BBBB..............cx.v.xvvv#                ",
    "..........BF.B...............x.v.xvvv#                ",
    ".................CCCCC##.####x...xvvv#                ",
    "CCCCCC...........CCCCC#v.v####v.vvvvv#                ",
    "CCCCCC...........CCCCC#v.v####v.vvvvv#                ",
    "CCCCC..F....F.........#v.vvvvvv.vvvvv#                ",
    "CCCCCC......vv....F.F.#v........vvvvv#                ",
    "............vv........#vvvvvvvvvvvvvv#                ",
    "GGGGGGGGGGGGGGGGGGGGGG#vvvvvvvvvvvvvv#                "
  ]
});
