/* ISOLATION map — edit by hand, or open editor.html and load this file.
   Chapter One, first deck: the inside of the service car, on its way down.
   Nothing here is a route. The doors are shut, the car is moving, and the only
   thing worth reading in it is the store the unit brought with it — [O] brings
   that up, anywhere on the deck, with no console to walk to. The segment ends
   when the sealed file on it gives way. */
ISO.register({
  "id": "Intermission",
  "name": "Service Car 14//CHAOS",
  "w": 49,
  "h": 56,
  "spawn": {"x": 13, "y": 1},
  "beacons": [],
  "carriage": true,
  "chapter": {"n": 1, "name": "ENTROPY"},
  "os": {
    "card": "PROLOUGE COMPLETE",
    "cardsub": "BEGIN CHAPTER ONE?",
    "files": [
      {"kind":"doc","name":"COMMUNICATIONS LOG","folder":"LOGS","pass":"","targets":[],"text":"COMMS LOG\n----\n00:00; COMMS WITH INSTELLAR COMMUNICATIONS NETWORK DISRUPTED.\n00:20; ATTEMPTING ACCESS TO ON-BOARD LONG-RANGE COMMUNICATIONS ANTENNA\n00:22; L-RCA ACCESS FAILED.\n--\n02:30; ATTEMPTING TO ACCESS SHIP-WIDE COMMUNICATIONS ARRAY\n02:35; COMMUNICATIONS ARRAY DAMAGED.\n02:45; COMMUNICATION RECIEVED FROM UNKNOWN SOURCE.\n02:55; QUARANTINED. SOURCE IDENTIFIED AS ONBOARD SHIP AI, CYGNUS."},
      {"kind":"locked","name":"SEALED COMMUNICATION ","folder":"","pass":"CYGNUS","targets":[],"text":"CONNECTION ESTABLISHED\nSOURCE: L.S.V COMMAND CORE, CYGNUS\n---\nHello?\nI don't think you have transmission capabilities considering your tumble through the roof in Engineering, but you should be able to pick this up.\n\nI'm Cygnus, the Mare's AI Core for their journey to 61 Cygnus and future travels across the system and constellation. We've been adrift for 863 years.\n\n25 years into our voyage, we were... boarded... At least, that's what I think happened. Whatever got onboard slaughtered the crew slowly, and it's been using the biomass from their bodies to fuel themselves until we get to 61 Cygni.\n\nYou have to get out of here. The fact you made it out of Engineering is testament enough. There should be a shuttle in the deployment bay. It has long range comms, and enough FTL fuel to get you back to Sol.\n\nBe safe.\n\n-CYGNUS \n"},
      {"kind":"doc","name":"TRAVEL LOG","folder":"LOGS","pass":"","targets":[],"text":"[LOG BEGIN]\n\nINITIAL DEPLOYMENT: [ERROR; UNKNOWN]\n\nNOTABLE EVENT: Gravitational Slingshot off of Procyon\n\nNOTABLE EVENT: Gravitational Slingshot off of Sirius\n\nNOTABLE EVENT: Entered SOL's SOI. Contacted by SAFFRON. Permitted Passage.\n\nNOTABLE EVENT: Gravitational Slingshot off of Ross 248. Now heading upwards.\n\nNOTABLE EVENT: Collision with unknown object.\n\n[LOG ENDS]"},
      {"kind":"doc","name":"Thoughts","folder":"PERSONAL","pass":"","targets":[],"text":"...\n...\n...\nI'm scared of this place.\nI don't like it.\nI've never been somewhere with the dead before.\nThe creatures are fine, but not the bodies.\nNo no no.\nNever bodies.\n---\nAt least I'm not alone out here. Going to try and find a way up to the ship's command. Probably find a map."},
      {"kind":"doc","name":"Memories","folder":"Personal","pass":"","targets":[],"text":"Fields of glistening wheat.\n...\nHmmm.\nNever been to planet for more than a couple of hours before. Especially not one with wheat.\n...\nHow strange."},
      {"kind":"doc","name":"SHIP-WIDE COMMUNICATIONS LOG","folder":"RECOVERED DOCUMENTS","pass":"","targets":[],"text":"07-09-25 (7 months, 9 days, 25 years into journey)\n------------------------\nENG-COM-NET: FAILED\nAGRI-COM-NET: UP.\nSEC-COM-NET: FAILED\nSCI-COM-NET: LOCKED DOWN\nGEN-COM-NET: UP\nCOMMAND-COM-NET: VIEW-ONLY\nPORT-COM-NET: FAILED."},
      {"kind":"doc","name":"Agriculture Resistence","folder":"RECOVERED DOCUMENTS","pass":"","targets":[],"text":"All survivors of D-Day, Agriculture Dome #12 is welcoming refuge. We can take up to 1200 more people before we will have to close down entry. \n\nDomes 1 through 7 have fallen to the invasion.\n\nDomes 8 through 9 are not open to refuge. \n\nSomething has happened to Domes 10 through 11."}
    ]
  },
  "props": {
    "13,0": {"title":"CAR 14 — FLOOR INDICATOR","text":"SERVICE CAR 14\n----\nDEPARTED: WATER TREATMENT, LOWER DECK\nDESCENDING.\n----\nDOORS: SEALED FOR TRANSIT\nCALL PLATE: NO ANSWER UNTIL THE CAR IS STOPPED\n----\nThe indicator counts nothing. Whatever deck this car is passing, it is not one the board has a number for.","desktop":false,"files":[{"kind":"app","name":"","folder":"","pass":"","targets":[],"text":""}],"card":"","cardsub":"","circuit":""},
    "37,7": {"dest":"AgriculturalDome12Fields","arrive":"DOME12-LANDING","fade":true,"card":"","cardsub":"","label":""},
    "15,8": {"title":"Poison?!?!","text":"THAT'S HOW IT ENDS?\nPOISON?\nFUCKING POISON?\nThose damn stalking bastards!\nTheir touch is toxic, FATAL.\nI felt off after I rushed past a horde of them in Engineering Command, but... FUCK!\nI can't die here, not like this.\n\nFUCK FUCK FUCK\n\n- Martin"},
    "5,12": {"open":false,"locked":false,"circuit":""},
    "6,12": {"open":false,"locked":false,"circuit":""},
    "7,12": {"open":false,"locked":false,"circuit":""},
    "8,12": {"open":false,"locked":false,"circuit":""},
    "9,12": {"open":false,"locked":false,"circuit":""},
    "10,12": {"open":false,"locked":false,"circuit":""},
    "11,12": {"open":false,"locked":false,"circuit":""},
    "12,12": {"open":false,"locked":false,"circuit":""},
    "13,12": {"open":false,"locked":false,"circuit":""},
    "14,12": {"open":false,"locked":false,"circuit":""},
    "15,12": {"open":false,"locked":false,"circuit":""},
    "16,12": {"open":false,"locked":false,"circuit":""},
    "17,12": {"open":false,"locked":false,"circuit":""},
    "18,12": {"open":false,"locked":false,"circuit":""},
    "19,12": {"open":false,"locked":false,"circuit":""},
    "20,12": {"open":false,"locked":false,"circuit":""},
    "21,12": {"open":false,"locked":false,"circuit":""},
    "35,15": {"title":"Considerations of Entropy","text":"[DATA CORRUPTED]\nWe'll all die eventually.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "25,25": {"dir":"down"},
    "27,25": {"dir":"down"},
    "29,25": {"dir":"down"},
    "31,25": {"dir":"down"},
    "33,25": {"dir":"down"},
    "35,25": {"dir":"down"},
    "37,25": {"dir":"down"},
    "39,25": {"dir":"down"},
    "41,25": {"dir":"down"},
    "43,25": {"dir":"down"},
    "25,29": {"dir":"right"},
    "29,29": {"dir":"right"},
    "33,29": {"dir":"right"},
    "37,29": {"dir":"right"},
    "41,29": {"dir":"right"},
    "25,31": {"dir":"down"},
    "27,31": {"dir":"down"},
    "29,31": {"dir":"down"},
    "31,31": {"dir":"down"},
    "33,31": {"dir":"down"},
    "35,31": {"dir":"down"},
    "37,31": {"dir":"down"},
    "39,31": {"dir":"down"},
    "41,31": {"dir":"down"},
    "43,31": {"dir":"down"},
    "16,33": {"open":false,"circuit":""},
    "16,34": {"open":false,"circuit":""},
    "16,35": {"open":false,"circuit":""},
    "25,35": {"dir":"right"},
    "29,35": {"dir":"right"},
    "33,35": {"dir":"right"},
    "37,35": {"dir":"right"},
    "41,35": {"dir":"right"},
    "15,36": {"title":"UNLABELLED CONSOLE","text":"No readable record.","desktop":true,"files":[{"kind":"doc","name":"Installation of New Locking Mechanism","folder":"","pass":"","targets":[],"text":"After a review of the incident on Tuesday in which 4 drunk engineers broke into the Agriculture Dome #12 Control room and caused it to excessively rain, we've installed a computer controlled password protected lock on the control room door. Do understand. The password is in the room below."},{"kind":"app","name":"ACCESS","folder":"","pass":"1179","targets":[{"x":16,"y":33},{"x":16,"y":34},{"x":16,"y":35}],"text":""}],"card":"","cardsub":"","circuit":""},
    "17,46": {"title":"Code from Drawer #34","text":"77\n"},
    "19,46": {"dir":"down"},
    "21,46": {"dir":"down"},
    "23,46": {"dir":"down"},
    "25,46": {"dir":"down"},
    "27,46": {"dir":"down"},
    "15,47": {"title":"Clean your Shit up","text":"If I walk into this damn room one more time and see the damn passcode library all fucked up again, I swear I will beat all of your asses when we land on 61.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "20,47": {"title":"Code from Drawer #09","text":"0918"},
    "22,47": {"title":"Code from Drawer #13","text":"1092"},
    "24,47": {"title":"HANDWRITTEN NOTE","text":"The ink has run. Nothing legible."},
    "26,47": {"title":"Code from Drawer #77","text":"1179"},
    "28,47": {"title":"Code from Drawer #85","text":"The ink has run. Nothing legible."},
    "17,49": {"title":"Code from Drawer #5","text":"44"},
    "19,50": {"dir":"right"},
    "23,50": {"dir":"right"},
    "27,50": {"dir":"right"},
    "20,51": {"title":"HANDWRITTEN NOTE","text":"3421"},
    "24,51": {"title":"HANDWRITTEN NOTE","text":"1232"},
    "28,51": {"title":"Code from Body","text":"The ink has run. Nothing legible."},
    "17,52": {"title":"HANDWRITTEN NOTE","text":"5063"},
    "19,52": {"dir":"right"},
    "23,52": {"dir":"right"},
    "27,52": {"dir":"right"}
  },
  "rows": [
    "  ###########c###########                        ",
    "  #==LLL============AA==#                        ",
    "  #=====================#                        ",
    "  #=====================#                        ",
    "  #=====================#                        ",
    "  #=====================#                        ",
    "  #=====================#   ###################  ",
    "  #=====================#   #........O........#  ",
    "  #============n========#   #.................#  ",
    "  #===========SXX======,#   #.................#  ",
    "  #===================,,#   #.................#  ",
    "  #===BB===========B====#   #.................#  ",
    "  ###GGGGGGGGGGGGGGGGG###   #.................#  ",
    "    #.................#     #/###////.........#  ",
    "    #.................#     #.......#.........#  ",
    "    #.................#     #......c#.........#  ",
    "    #.................#     #.......#.........#  ",
    "    #.................#     #......./.........#  ",
    "    #.................#     ###/####/.....CCCC#  ",
    "    #.................#     #.............CCCC#  ",
    "    #.................#     #.B.BB........CCCC#  ",
    "     ##.............##      #BBBBB........CCCC#  ",
    "       ##.........##        #.B.BB........CCCC#  ",
    "         #.......#    #######.................#  ",
    "         #.......#    #.......................#  ",
    "          #.....#     #..D.D.D.D.D.D.D.D.D.D..#  ",
    "          #.....#     #.......................#  ",
    "          #.....#     #.......................#  ",
    "          #.....#     #.......................#  ",
    "          #.....#     #..D...D...D...D...D....#  ",
    "          #.....#     #.......................#  ",
    "          #.....#     #..D.D.D.D.D.D.D.D.D.D..#  ",
    "          #.....#######.......................#  ",
    "          #.....%.............................#  ",
    "          #.....%.............................#  ",
    "          #.....%........D...D...D...D...D....#  ",
    "          #....c######........................#  ",
    "          #.....#    ##########################  ",
    "          #.....#                                ",
    "          #.....#                                ",
    "          #.....#                                ",
    "          #.....#                                ",
    "          #.....#                                ",
    "          #.....#                                ",
    "          #.....###############                  ",
    "          #.....+.,..,.,..,,..#                  ",
    "          #.....+n,D,D.D,D,D,,#                  ",
    "          #....c#.,.n.n.n.n.n,#                  ",
    "          #.....#.,.....,...,,#                  ",
    "          #.....#n,.,..,,.....#                  ",
    "          #.....#.,D..,D..,D..#                  ",
    "          #.....#.,.n,,.n.,,nS#                  ",
    "          #.....#n,D..,D..,D..#                  ",
    "          #####################                  ",
    "                                                 ",
    "                                                 "
  ]
});
