/* ISOLATION map — edit by hand, or open editor.html and load this file.
   A hundred and twenty squares of hallway, with eleven little rooms down
   each side of it and a console at the far end that seals the last file. */
ISO.register({
  "id": "PostMortum",
  "name": "POST MORTUM // ONE HALLWAY, AND WHAT IS FILED OFF IT",
  "w": 122,
  "h": 25,
  "spawn": {"x": 1, "y": 12},
  "beacons": [],
  "chapter": {"n": 3, "name": "POST MORTUM"},
  "props": {
    "112,2": {"label":"OBSERVATION PORT"},
    "113,2": {"label":""},
    "114,2": {"label":""},
    "115,2": {"label":""},
    "116,2": {"label":""},
    "117,2": {"label":""},
    "118,2": {"label":""},
    "119,2": {"label":""},
    "64,3": {"reach":3,"label":"SCRUB LINE","circuit":""},
    "2,4": {"label":"POST-MORTEM RECEPTION"},
    "3,4": {"label":""},
    "4,4": {"label":""},
    "5,4": {"label":""},
    "6,4": {"label":""},
    "7,4": {"label":""},
    "9,4": {"label":""},
    "13,4": {"dir":"right","label":"ADMISSIONS"},
    "68,4": {"dir":"right"},
    "90,4": {"dir":"right"},
    "95,4": {"dir":"right"},
    "107,4": {"label":""},
    "108,4": {"label":""},
    "30,5": {"dir":"right","hand":true,"eye":true,"label":"DRAWER 11"},
    "47,5": {"label":"SLAB ONE"},
    "48,5": {"label":""},
    "49,5": {"label":""},
    "50,5": {"label":""},
    "114,5": {"dir":"up"},
    "117,5": {"dir":"up"},
    "5,6": {"title":"Pinned to the counter","text":"If you are reading this you came down the hall, which means you already walked past twenty-two doors.\n\nNothing on this deck is dangerous on its own. It is what the deck was for that people find hard.\n\nSign in. Nobody checks any more, but sign in.\n\n- DECK WATCH"},
    "68,6": {"dir":"right"},
    "80,6": {"label":"SLAB THREE"},
    "81,6": {"label":""},
    "82,6": {"label":""},
    "83,6": {"label":""},
    "84,6": {"label":""},
    "97,7": {"label":""},
    "9,8": {"label":""},
    "18,8": {"title":"ADMISSIONS","text":"INTAKE, LAST SEVEN DAYS\n\n07-28-25   3 CREW        THEATRE ONE\n07-29-25   1 CREW        THEATRE ONE\n07-30-25   9 UNIDENTIFIED   HELD, WARD ONE\n07-31-25   —\n08-01-25   —\n08-02-25   —\n08-03-25   —\n\nNo attendant has signed the book since 07-30-25.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "24,8": {"label":"DRAWER 07"},
    "47,8": {"label":"SLAB TWO"},
    "48,8": {"label":""},
    "49,8": {"label":""},
    "50,8": {"label":""},
    "60,8": {"label":"SCRUB CUPBOARD"},
    "71,8": {"title":"TAG BOOK","text":"Whoever is on the console at the end of the hall keeps sealing the file and forgetting the word by the next watch.\n\nSo: it is her name. It has been her name since we sailed, it will be her name at the end of it.\n\nHOLLOWAY.\n\nWrite it down somewhere that is not the console, she says. This is somewhere that is not the console."},
    "86,8": {"dir":"left","hand":true,"eye":false,"label":"SLAB THREE"},
    "90,8": {"title":"DECK SCREEN","text":"A loop, on a deck nobody watches it on.\n\n\"— and the Board thanks the families of the crew for their patience. Transit is long. Grief is longer. The Quiet Room on every deck is yours for as long as you need it.\"\n\nThe loop starts again.","label":"","circuit":""},
    "95,8": {"wake":17,"range":30,"label":"QUIET ROOM"},
    "112,8": {"title":"Left on the sill","text":"Twenty-five years out and the window looks the same as it did at the yard.\n\nThat is the part nobody warns you about. Not the dark. The sameness.\n\n- PATRICA"},
    "119,8": {"label":""},
    "36,9": {"title":"RECORDS","text":"POST-MORTEM RECORD 4411\n\nCAUSE OF DEATH: the report has been amended four times. The last amendment removes the cause of death and leaves the heading.\n\nSIGNED: HOLLOWAY, DECK OFFICER","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "46,9": {"dir":"right","hand":false,"eye":true,"label":"UNTAGGED"},
    "4,11": {"title":"RECEPTION","text":"RECEPTION\nPOST MORTUM. ONE WAY IN, ONE WAY DOWN THE HALL."},
    "15,11": {"title":"ADMISSIONS","text":"ADMISSIONS\nNAME, NUMBER, DECK. IN THAT ORDER."},
    "26,11": {"title":"COLD STORE 1","text":"COLD STORE 1\nDRAWERS 01–24. KEEP THE DOOR SHUT."},
    "37,11": {"title":"RECORDS","text":"RECORDS\nPAPER COPY HELD 25 YEARS."},
    "48,11": {"title":"THEATRE ONE","text":"THEATRE ONE\nSTERILE. NO CHASSIS PAST THE LINE."},
    "59,11": {"title":"SCRUB","text":"SCRUB\nHANDS, ARMS, TOOLS. IN THAT ORDER."},
    "70,11": {"title":"TAGGING","text":"TAGGING\nNOTHING LEAVES THIS DECK UNTAGGED."},
    "81,11": {"title":"THEATRE TWO","text":"THEATRE TWO\nSTERILE. LAMP RUNS ON THE HOUR."},
    "92,11": {"title":"QUIET ROOM","text":"QUIET ROOM\nFOR THOSE WHO HAVE JUST BEEN TOLD."},
    "103,11": {"title":"STORES","text":"STORES\nSHEETING, BAGS, TRAYS. SIGN FOR THEM."},
    "114,11": {"title":"OBSERVATION","text":"OBSERVATION\nPORT SIDE. THE STARS DO NOT MOVE MUCH."},
    "1,12": {"dest":"CommandCommunicationArray","arrive":"","fade":false,"card":"","cardsub":"","label":"","circuit":""},
    "120,12": {"title":"POST-MORTEM CONSOLE","text":"No readable record.","desktop":true,"files":[{"kind":"doc","name":"DECK NOTICE.DOC","folder":"","pass":"","targets":[],"text":"POST MORTUM — DECK NOTICE\n\nOne hallway. Twenty-two rooms off it. Everything that stops aboard this ship stops here first and is written down before it is anything else.\n\nThe hall lights run on the ship's own supply and cannot be switched off from this deck. That was thought to be a kindness."},{"kind":"doc","name":"ROUNDS.LOG","folder":"LOGS","pass":"","targets":[],"text":"07-29-25  Rounds walked. 22 doors. All secure.\n07-30-25  Rounds walked. 22 doors. All secure.\n07-31-25  Rounds walked. 23 doors.\n08-01-25  Rounds not walked.\n08-02-25  Rounds not walked.\n08-03-25  Rounds not walked."},{"kind":"doc","name":"INTAKE 07-30-25.DOC","folder":"LOGS","pass":"","targets":[],"text":"NINE UNIDENTIFIED BIOLOGICAL ORGANISMS, received from the elevator, held WARD ONE.\n\nNone of the nine is crew. None of the nine is on the manifest. Two of the nine were still moving at the end of the watch and the book has no column for that, so it has not been written down.\n\nSIGNED: HOLLOWAY, DECK OFFICER"},{"kind":"locked","name":"POST MORTEM.SEALED","folder":"","pass":"HOLLOWAY","targets":[],"text":"There is no cause of death on this deck any more. There is a hallway, and rooms off it, and a word that opens the last file in the drawer.\n\nWhoever you are: you walked the whole of it. That is the whole of what there is to walk, for now.\n\nThe rest of the ship is drawn, somewhere. It is simply not drawn yet.\n\n- HOLLOWAY, DECK OFFICER, who signed for all of them"}],"card":"THAT IS ALL THERE IS","cardsub":"Post Mortum — the rest of the ship is not drawn yet","circuit":""},
    "7,13": {"title":"SECURITY POST","text":"SECURITY POST\nDECK WATCH. ONE OFFICER, ALL HOURS."},
    "18,13": {"title":"LOCKER ROOM","text":"LOCKER ROOM\nCIVILIAN CLOTHES OFF THIS DECK."},
    "29,13": {"title":"WARD ONE","text":"WARD ONE\nHOLDING. NOT FOR THE LIVING."},
    "40,13": {"title":"WARD TWO","text":"WARD TWO\nHOLDING. DOOR STAYS SHUT."},
    "51,13": {"title":"INCINERATOR","text":"INCINERATOR\nBURN LIST SIGNED BY TWO."},
    "62,13": {"title":"PLANT","text":"PLANT\nDECK AIR AND DECK COLD. LOUD ROOM."},
    "73,13": {"title":"MESS","text":"MESS\nEAT HERE, NOT IN THE THEATRES."},
    "84,13": {"title":"COLD STORE 2","text":"COLD STORE 2\nDRAWERS 25–48. OVERFLOW ONLY."},
    "95,13": {"title":"BUNKS","text":"BUNKS\nNIGHT ATTENDANT. KNOCK FIRST."},
    "106,13": {"title":"WASTE","text":"WASTE\nSHARPS IN THE RED BIN."},
    "117,13": {"title":"VIEWING","text":"VIEWING\nFAMILIES THIS WAY. QUIET PLEASE."},
    "9,16": {"title":"DECK WATCH","text":"WATCH LOG — FINAL ENTRY\n\nHall lights on the hour, both ends walked, all twenty-two doors tried.\n\nSomething is walking the hall with me. It does not use the doors and it does not make any noise I can put a direction on.\n\nI am not walking the hall again.","desktop":false,"files":[],"card":"","cardsub":"","circuit":""},
    "24,16": {"dir":"right"},
    "35,16": {"dir":"right"},
    "42,16": {"dir":"down"},
    "46,16": {"label":""},
    "64,16": {"label":"","circuit":""},
    "69,16": {"dir":"right"},
    "75,16": {"label":""},
    "79,16": {"dir":"right","hand":false,"eye":true,"label":"DRAWER 29"},
    "86,16": {"label":"DRAWER 33"},
    "90,16": {"dir":"right"},
    "108,16": {"label":""},
    "113,16": {"label":""},
    "119,16": {"label":""},
    "46,17": {"label":""},
    "116,17": {"title":"VIEWING","text":"THE BOARD REGRETS.\n\nTHE BOARD REGRETS.\n\nTHE BOARD REGRETS."},
    "20,18": {"label":"LOCKER 19"},
    "24,18": {"dir":"right"},
    "39,18": {"wake":12,"range":0,"label":"WARD TWO"},
    "61,18": {"hears":24,"range":0,"label":"PLANT"},
    "82,18": {"dir":"right"},
    "5,19": {"label":"WATCH LOCKER"},
    "35,19": {"dir":"right"},
    "64,19": {"label":"","circuit":""},
    "73,19": {"label":""},
    "74,19": {"label":""},
    "75,19": {"label":""},
    "90,19": {"dir":"right"},
    "24,20": {"dir":"right"},
    "30,20": {"dir":"right"},
    "68,20": {"dir":"right"},
    "95,20": {"title":"Folded under a pillow","text":"Day shift says the hall is only a hall.\n\nDay shift has never stood at the reception end with the lights off and counted the doors twice and got a different number.\n\nI am putting in for a transfer to Agriculture. Anywhere with a sky painted on the ceiling."},
    "112,22": {"label":"VIEWING PORT"},
    "113,22": {"label":""},
    "114,22": {"label":""},
    "115,22": {"label":""},
    "116,22": {"label":""},
    "117,22": {"label":""},
    "118,22": {"label":""},
    "119,22": {"label":""}
  },
  "rows": [
    "ṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽ",
    "ṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽ",
    "################################################################################################################ïïïïïïïï##",
    "#``````````#..........#.LLLLLL...#..........#..........#........$.#..........#..........#``````````#..........#..........#",
    "#`))))))`5`#.J......a.#..........#.AAAAAAA..#.......ł..#.L....111.#.D......A.#.ł......ł.#`U``7`6```#.CCC...ƀƀ.#..........#",
    "#``````````#..........#.......ÿ..#..........#..8888....#.L....111.#..........#..........#``````````#.CCC......#...6..6...#",
    "#````n`````#.AAA......#..........#..........#........;.#.L........#.ś........#..88888...#``````````#..........#..........#",
    "#`aa```````#..........#...;;.....#.AAAAAAA..#.......;;.#..........#..........#..........#````````5`#......CCC.#..........#",
    "#````````5`#......c.L.#.{......L.#..........#..8888....#....{.....#....n..XX.#.;;.....ÿ.#`m````ż```#.BB...CCC.#.n......5.#",
    "#``````````#..........#..........#.Bc.....B.#.ÿ........#..........#..........#.;........#``````````#..........#..........#",
    "#####+##########+##########+##########+##########+##########+##########+##########+##########+##########+##########+######",
    "#===N=========,N,===ł=====N========ŵŵN=========,N,========;N=''=======N=========ďN======,,==N========ł=N======ðð==N======#",
    "#^===============================''========================================================'============================I#",
    "#======N==========N======;;==N,=========N=ď========N==ðð======N===ł=====,N==ŵ=======N==========N;=======,,N==========N===#",
    "######+##########+##########+##########+##########+##########+##########+##########+##########+##########+##########+#####",
    "#..........#.LLLL.LLL.#..........#..........#..........#.ooo......#..........#..........#..........#..........#``````````#",
    "#.LL....ac.#..........#.Z........#.Z......Z.#.ƀ....!!!.#........9.#.at.....5.#.ÿ......{.#.Z......L.#.ððð....ƀ.#``5`````5`#",
    "#..........#..........#.......;;.#..........#.ƀ....!!!.#..........#....a.....#..........#........L.#.ððð......#`````N````#",
    "#..........#..a.....{.#.Z......;.#.....e....#......!!!.#.....4....#..........#....ś.....#..........#..........#``````````#",
    "#....{.....#..........#..........#.Z........#..........#.ðð.....9.#......888.#..........#.Z........#.......ŵŵ.#``aaa`aa``#",
    "#..........#..........#.Z.....ś..#....;;....#...B...XX.#..........#.U........#..........#......n...#.X...ď....#``````````#",
    "#..........#.LLLLLLLL.#..........#..........#..........#..........#..........#.LLLLLL...#..........#..........#``````````#",
    "################################################################################################################ïïïïïïïï##",
    "ṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽ",
    "ṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽṽ"
  ]
});
