/* ISOLATION map — edit by hand, or open editor.html and load this file. */
ISO.register({
  "id": "tutorial",
  "name": "Landing Site — Node 77",
  "w": 54,
  "h": 27,
  "spawn": {"x": 26, "y": 22},
  "beacons": [{"x": 7, "y": 8}],
  "props": {
    "47,12": {"open":false},
    "4,13": {"target":{"x":3,"y":15},"label":"WEST CAP"},
    "46,13": {"title":"TRANSIT CONTROL","text":"NODE 77 / EAST TRANSIT\nLanding above is sealed. Drive the bulkhead from the control beside this console.\nBay 2 platform answers its own call. Stand on the plating first.","desktop":true},
    "48,13": {"target":{"x":47,"y":12},"label":"LANDING"},
    "0,15": {"title":"SURFACE RECORD 0-1","text":"NODE 77 / WEST CAP\nPressure holds. Nothing logged beyond this wall since arrival.\nWhoever sealed it did so from this side.","desktop":false},
    "3,15": {"open":false},
    "49,17": {"target":{"x":43,"y":18},"label":"BAY 2 RETURN"},
    "42,18": {"target":{"x":43,"y":18},"label":"BAY 2"},
    "43,18": {"dir":"right","dist":6}
  },
  "rows": [
    "                                                      ",
    "                  ####################                ",
    "                  #...............~!!#                ",
    "   ##########     #...............~!!#                ",
    "   #~!!!!!!~#     #...............~~~#                ",
    "   #~~~~~~~~#     #..................#                ",
    "   #........#     #..................#                ",
    "   #........#     #..................#                ",
    "   #........#     #..................#                ",
    "   #........#     #..................#   #############",
    "   #........#     #..................#   #...........#",
    "   ###.######     ####......##########   #.........^.#",
    "     #.#             #......#            ######%######",
    "####b#+##################+####################c.b#####",
    "#..#=...............=..,....,........~!!!............#",
    "c..%................................~~!!!............#",
    "#..#..=......................,......~~!!!###+#########",
    "#..#.........=.......,...............~!!!#...####b...#",
    "##########################+###############bTvvvvv....#",
    "                      #..........#       ########....#",
    "                      #..........#       ########.xx.#",
    "                      #..........#       ########.vv.#",
    "                      #..........#       ########....#",
    "                      #..........#       #############",
    "                      ############                    ",
    "                                                      ",
    "                                                      "
  ]
});
