/* ISOLATION map — edit by hand, or open editor.html and load this file. */
ISO.register({
  "id": "WaterTreatmentTop",
  "name": "WaterTreatmentTop",
  "w": 100,
  "h": 92,
  "spawn": {"x": 92, "y": 4},
  "beacons": [],
  "under": {"deck": "WaterTreatmentBottom", "dx": 0, "dy": 0},
  "props": {
    "67,3": {"dir":"right"},
    "72,3": {"dir":"up"},
    "17,4": {"dir":"right"},
    "64,4": {"dir":"down"},
    "7,5": {"dir":"down"},
    "17,5": {"dir":"right"},
    "14,6": {"dir":"right"},
    "19,6": {"dir":"down"},
    "22,6": {"dir":"right"},
    "68,6": {"dir":"down"},
    "4,7": {"dir":"down"},
    "9,7": {"dir":"right"},
    "29,7": {"dir":"right"},
    "63,7": {"dir":"right"},
    "15,8": {"dir":"right"},
    "22,8": {"dir":"right"},
    "6,9": {"dir":"down"},
    "20,9": {"dir":"down"},
    "5,10": {"rating":"a15","label":""},
    "12,11": {"dir":"left"},
    "14,11": {"dir":"down"},
    "31,11": {"dir":"down"},
    "19,12": {"dir":"down"},
    "3,13": {"dir":"left"},
    "8,13": {"dir":"down"},
    "60,13": {"title":"Welcome to Water Treatment!!!","text":"Hello, Beginning Engineers, and welcome to the L.S.V's Water Treatment Facility. While most other ships use standard Life Support systems for water repurposement, because the Mare has been sent for colonization, it has been equipped with a Water Treatment Facility for future use on planet.\n\nDue to the size of the facility, exiting through this door will bring you onto the catwalks above the primary collection tanks. Be careful not to fall into the water below, but our automated safety systems will help you out quickly if you do!  ","desktop":false,"circuit":""},
    "10,14": {"dir":"down"},
    "48,14": {"targets":[{"x":47,"y":17},{"x":48,"y":17},{"x":49,"y":17},{"x":59,"y":14},{"x":59,"y":15},{"x":59,"y":16},{"x":67,"y":39},{"x":68,"y":39},{"x":69,"y":39},{"x":70,"y":39},{"x":71,"y":39},{"x":72,"y":39},{"x":73,"y":39}],"label":"","circuit":"BUTTON"},
    "59,14": {"open":false,"circuit":""},
    "89,14": {"dir":"down"},
    "18,15": {"dir":"down"},
    "59,15": {"open":false,"circuit":""},
    "12,16": {"dir":"down"},
    "29,16": {"dir":"right"},
    "50,16": {"ways":[{"circuit":"BUTTON","rating":"a15"}],"label":""},
    "59,16": {"open":false,"circuit":""},
    "82,16": {"dir":"down"},
    "92,16": {"dir":"up"},
    "3,17": {"dir":"left"},
    "47,17": {"open":false,"circuit":""},
    "48,17": {"open":false,"circuit":""},
    "49,17": {"open":false,"circuit":""},
    "60,17": {"title":"Don't","text":"It's out there.\nWe learned the hard way.\nThis is the only safe haven"},
    "86,17": {"dir":"left"},
    "95,17": {"dir":"left"},
    "8,19": {"dir":"right"},
    "19,19": {"dir":"down"},
    "80,19": {"dir":"right"},
    "90,19": {"dir":"right"},
    "77,20": {"dir":"down"},
    "95,20": {"dir":"up"},
    "10,21": {"dir":"left"},
    "16,21": {"dir":"right"},
    "28,21": {"dir":"down"},
    "73,21": {"dir":"right"},
    "81,21": {"dir":"right"},
    "86,21": {"dir":"right"},
    "20,22": {"dir":"down"},
    "91,22": {"dir":"left"},
    "96,22": {"dir":"down"},
    "77,23": {"dir":"right"},
    "81,24": {"targets":[{"x":59,"y":16},{"x":59,"y":15},{"x":59,"y":14}],"label":"","circuit":""},
    "82,24": {"dir":"up"},
    "21,25": {"dir":"right"},
    "67,26": {"dir":"right"},
    "70,26": {"dir":"right"},
    "77,26": {"ability":"motion","label":"","circuit":""},
    "88,26": {"rating":"a15","label":""},
    "67,27": {"dir":"right"},
    "70,27": {"dir":"right"},
    "77,27": {"range":2,"armed":true,"objective":"","label":"","circuit":""},
    "67,28": {"dir":"right"},
    "70,28": {"dir":"right"},
    "77,28": {"title":"please oh god please","text":"Spare us\nSpare us\nSpare us\nSpare us\nSpare us\nSpare us\nSpare us\nSpare us","desktop":false,"circuit":""},
    "67,29": {"dir":"right"},
    "70,29": {"dir":"right"},
    "67,30": {"dir":"right"},
    "70,30": {"dir":"right"},
    "67,31": {"dir":"right"},
    "70,31": {"dir":"right"},
    "12,32": {"dir":"down"},
    "14,32": {"dir":"down"},
    "16,32": {"dir":"down"},
    "18,32": {"dir":"down"},
    "20,32": {"dir":"down"},
    "22,32": {"dir":"down"},
    "24,32": {"dir":"down"},
    "26,32": {"dir":"down"},
    "67,32": {"dir":"right"},
    "70,32": {"dir":"right"},
    "67,33": {"dir":"right"},
    "70,33": {"dir":"right"},
    "67,34": {"dir":"right"},
    "70,34": {"dir":"right"},
    "88,34": {"title":"HANDWRITTEN NOTE","text":"The ink has run. Nothing legible."},
    "89,34": {"dir":"right"},
    "67,35": {"dir":"right"},
    "70,35": {"dir":"right"},
    "89,35": {"dir":"right"},
    "4,36": {"dir":"right"},
    "12,36": {"dir":"down"},
    "14,36": {"dir":"down"},
    "16,36": {"dir":"down"},
    "18,36": {"dir":"down"},
    "20,36": {"dir":"down"},
    "22,36": {"dir":"down"},
    "24,36": {"dir":"down"},
    "26,36": {"dir":"down"},
    "67,36": {"dir":"right"},
    "70,36": {"dir":"right"},
    "89,36": {"dir":"right"},
    "67,37": {"dir":"right"},
    "70,37": {"dir":"right"},
    "19,38": {"rating":"a15","label":""},
    "67,38": {"dir":"right"},
    "70,38": {"dir":"right"},
    "67,39": {"open":false,"locked":false,"circuit":""},
    "68,39": {"open":false,"locked":false,"circuit":""},
    "69,39": {"open":false,"locked":false,"circuit":""},
    "70,39": {"open":false,"locked":false,"circuit":""},
    "71,39": {"open":false,"locked":false,"circuit":""},
    "72,39": {"open":false,"locked":false,"circuit":""},
    "73,39": {"open":false,"locked":false,"circuit":""},
    "78,39": {"open":false,"locked":false,"circuit":""},
    "79,39": {"open":false,"locked":false,"circuit":""},
    "80,39": {"open":false,"locked":false,"circuit":""},
    "81,39": {"open":false,"locked":false,"circuit":""},
    "82,39": {"open":false,"locked":false,"circuit":""},
    "83,39": {"open":false,"locked":false,"circuit":""},
    "84,39": {"open":false,"locked":false,"circuit":""},
    "89,39": {"open":false,"locked":false,"circuit":""},
    "90,39": {"open":false,"locked":false,"circuit":""},
    "91,39": {"open":false,"locked":false,"circuit":""},
    "92,39": {"open":false,"locked":false,"circuit":""},
    "93,39": {"open":false,"locked":false,"circuit":""},
    "94,39": {"open":false,"locked":false,"circuit":""},
    "95,39": {"open":false,"locked":false,"circuit":""},
    "70,43": {"title":"If you are seeing this.","text":"It's out\n"},
    "1,44": {"dir":"right"},
    "1,45": {"dir":"right"},
    "6,45": {"dir":"right"},
    "2,46": {"dir":"right"},
    "2,47": {"dir":"right"},
    "6,47": {"dir":"right"},
    "66,47": {"ways":[{"circuit":"BUTTON1","rating":"a15"}],"label":""},
    "1,48": {"dir":"right"},
    "6,48": {"dir":"right"},
    "49,48": {"targets":[{"x":49,"y":49},{"x":48,"y":49},{"x":47,"y":49}],"label":"","circuit":"BUTTON1"},
    "47,49": {"open":false,"circuit":""},
    "48,49": {"open":false,"circuit":""},
    "49,49": {"open":false,"circuit":""},
    "1,50": {"dir":"right"},
    "5,50": {"dir":"right"},
    "3,51": {"dir":"right"},
    "5,52": {"dir":"right"},
    "2,61": {"dir":"right"},
    "6,61": {"dir":"right"},
    "47,61": {"targets":[{"x":48,"y":79}],"label":"","circuit":"TRAMBUTTON"},
    "47,62": {"open":false,"circuit":""},
    "48,62": {"open":false,"circuit":""},
    "49,62": {"open":false,"circuit":""},
    "15,64": {"dir":"down"},
    "18,64": {"dir":"down"},
    "1,65": {"dir":"down"},
    "7,65": {"dir":"right"},
    "17,65": {"dir":"down"},
    "10,66": {"dir":"down"},
    "3,67": {"dir":"down"},
    "4,67": {"dir":"right"},
    "7,67": {"dir":"down"},
    "16,67": {"dir":"down"},
    "19,67": {"dir":"right"},
    "30,67": {"targets":[{"x":49,"y":62},{"x":48,"y":62},{"x":47,"y":62}],"label":"","circuit":""},
    "18,68": {"dir":"right"},
    "30,68": {"title":"LOCKDOWN ORDER","text":"WATER TREATMENT IS LOCKED DOWN\n----\nATTACHED MESSAGE READS:\n\nTHE L.S.V MARE IS UNDER ATTACK BY AN UNKNOWN BIOLOGICAL FORCE. FIRST REPORTS INDICATE THAT THE ATTACK STARTED WITHIN THE ENGINEERING SECTOR. ALL ROUTES OUT OF THE SECTOR HAVE BEEN LOCKED DOWN UNTIL FURTHER NOTICE.\n\nALL PERSONNEL REPORT TO SECURITY FOR SAFE-KEEPING.","desktop":false,"circuit":""},
    "18,69": {"dir":"down"},
    "9,70": {"dir":"left"},
    "6,71": {"dir":"right"},
    "48,79": {"dir":"up","dist":18,"circuit":""},
    "95,82": {"dir":"left"},
    "96,82": {"title":"For Mom","text":"I'm so sorry.\nI should've been better.","desktop":false,"circuit":""},
    "97,82": {"ways":[{"circuit":"TRAMBUTTON","rating":"a15"}],"label":""},
    "48,86": {"title":"LITTLE WORM","text":"LITTLE WORM\nDIGGING THROUGH THE CARCESS\nDON'T THINK I HAVEN'T SEEN YOU.","desktop":false,"circuit":""},
    "48,89": {"dest":"WaterTreatmentBottom","arrive":"","fade":false,"label":""}
  },
  "rows": [
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv##################################",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv##;;;;;;;;;;;;X....................#",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv##;;;;;;;;;;;;;;X....................#",
    "#########################vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;Y;;;;Y;;;;XX....................#",
    ".................D.......##vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;Y;;;;;;;;;;;XX.....................#",
    ".......D.........D.........##vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;;;;;;;;XXX......................#",
    "...;;;........Y....D..D......###vvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;;Y;;;;XX........................#",
    "..;;Y;...Y...................Y;;#vvvvvvvvvvvvvvvvvvvvvvvvvv#;;;Y;;;;;;;;XX...S.....................#",
    "...;.;.........Y......D......X;;#vvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;;;;XXXX..........................#",
    "...;;;D...........;;D........X;;#vvvvvvvvvvvvvvvvvvvvvvvvvv#;X;;;;;;;XS...........S................#",
    "...;;f............;;.........X;;;#vvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;XXXX.............................#",
    ".....;......Y.D...;;.........X;Y;#vvvvvvvvvvvvvvvvvvvvvvvvv#;;;XXXX.....S....S.....................#",
    ";;;;;.............;D~........X;;;;#vvvvvvvvvvvvvvvvvvvvvvvv#XXXX......;;...;;.....S................#",
    ";..Y;;..Y.........;.~.......XX;;;;#vvvvxxxxxxxxxxxxxxxxxxxx#c.S......S.....S;.........XXXXXXXXXXXXX#",
    ";;;;;;....D......;;.~......XXX;;;;;vvvv:::::::::b::::::::::%...............S;...XXXXXXX;;Y;;;;;;;;;#",
    "..;;.............;D~~......XXX;;;;;vvvv::::::::::::::::::::%..;;.......S;.....XXX;;;;;;;;;;;;;;;;;;#",
    ";;;;;.......D....;.~~......XXY;;;;;vv:::::::::::::u::::::::%..S;.......;;....XX;;;Y;;;;;;;;;Y;;;;;;#",
    ";..Y;............;.~~......XXX;;;;#vvxxxxxxxxxx%%%xxxxxxxxx#n..............XXX;;;;;;;;Y;;;;;;;;Y;;;#",
    ";;;;;............;;~~......XXX;;;;#vvvvvvvvvvvx:::x........#...........S.XXX;;;;;;;;;;;;;;;;;;;;;;;#",
    ".;;;....D........;;D~.......XX;;;#vvvvvvvvvvvvx:::x.........#....S......XX;;;;;;Y;;;;;;;;;Y;;;;;;;;#",
    ".......;;;;;.....;;.~.........;;##vvvvvvvvvvvvx:::x.........#.........XXX;;;;Y;;;;;;;;;;;;;;;;;Y;;;#",
    ".......;..Y;....Y;;.~.......Y;;;#vvvvvvvvvvvvvx:::x..........#..S....XX;;Y;;;;;;;Y;;;;Y;;;;;;;;;;;;#",
    ".......;;;;;......;;D........;;;#vvvvvvvvvvvvvx:::x..........#.....XXX;;;;;;;;;;;;;;;;;;;;;Y;;;;Y;;#",
    "..................;;.........###vvvvvvvvvvvvvvx:::x...........##...X;;;;;;;;;Y;;;;;;;;;;;;;;;;;;;;;#",
    "..................;;.......##vvvvvvvvvvvvvvvvvx:::x.............##.X;;;;;;;;;;;;;bY;;;;;;;;;;;;;;;;#",
    "..................;;;D...##vvvvvvvvvvvvvvvvvvvx:::x...............##################################",
    "#########################vvvvvvvvvvvvvvvvvvvvvx:::x...............#Y..Y..;;##M......;;##f..;..;;.###",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::x...............#Y..Y..;;##*......;;##...;;.;;;###",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::x...............#Y..Y..;;##c......;;##...;;;;;;###",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::x...............#Y..Y..;;##CCC...;;;##.;;;;;;;;###",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::x...............#Y..Y..;;##CCC;;;;;;##;;;;;;;;;###",
    "################################vvvvvvvvvvvvvvx:::x...............#Y..Y..;;##CCC;;;;;;##..;;;;;;;###",
    "#...;.......D.D.D.D.D.D.D.D....#vvvvvvvvvvvvvvx:::x...............#Y..Y..;;##;;;;CCCCC##.;;;;;;;;###",
    "#...;;.........................#vvvvvvvvvvvvvvx:::x...............#Y..Y..;;##.SS;CCCCC##BBB;;;;;;###",
    "#..;;;;........................#vvvvvvvvvvvvvvx:::x...............#Y..Y..;;##...;CCCCC##nY..BBB;;###",
    "#;;;;;;;;;....................L#vvvvvvvvvvvvvvx:::x...............#Y..Y..;;##...;CCCCC##;Y..BBB;;###",
    "#.;;Y..;;...D.D.D.D.D.D.D.D....#vvvvvvvvvvvvvvx:::x...............#Y..Y..;;##BBB......##;Y..BBB;.###",
    "#XX;;;;;;......................#vvvvvvvvvvvvvvx:::x...............#Y..Y..;;##BBB......##LLLLLLL;.###",
    "#XX.;.;.XXX........f...........#vvvvvvvvvvvvvvx:::x...............#Y..Y..;;##BBB......##.........###",
    "#XXX;...X#######################vvvvvvvvvvvvvvx:::x...............#GGGGGGG####GGGGGGG####GGGGGGG####",
    "#XXXX..XX#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::x..............x.;;;;;;;;.........................",
    "#XXXX.XXX#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::x..............x...;;;;;..........................",
    "#XXXX.XXX#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xxxxxxxxxxxxxxxx...;;;;...........................",
    "#XXXX.XXX#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::::::::::::::::::....n.............................",
    "#D..X.AAA#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::::::::::::::::::..................................",
    "#D..X.D..#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::::::::::::::::::..................................",
    "#BD...BBB#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xxxxxxxxxxxxxxxx..................................",
    "#BD...D..#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvxu.................................",
    "#D....D..#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx::bxvvvvvvvvvvvvvvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "#BBB.....#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx%%%xvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "#D..BD...#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "#..D.....#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "#....D...#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "#........#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:::xvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "#........+::::::::::::::::::::::::::::::::::::::::xvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "#........+::::::::::::::::::::::::::::::::::::::::xvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "#........+::::::::::::::::::::::::::::::::::::::::xvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "/vvvvvvvv#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:::xvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "/vvvvvvvv/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xxxxxxxxxxxxxxxxxxxxxxxxxxxvvvvvvvvvvvvvvvvvvvvvvv",
    "/vvvvvvvv/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::::::::::::::::::::::::::::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#LL....LL#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::::::::::::::::::::::::::::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#CD...D..#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvxb::::::::::::::::::::::::::::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#CC....CC#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx%%%xxxxxxxxxxxxxxxxxxxxxxx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#CC....CC#######################vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#CC....CCCCCC.;Y;SYXX;;........#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#D.....D.....;;;;Y.XX;;........#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#.........D..L;;;..XX;;........#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#..DD..D......L;Y.XYX;;.......b#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#.............L;;XYXX;;.......c#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#.............L;;XYXX;;........#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#........D.....L;XXXX;;........#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "#.....D........L;XXXX;;........#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "################################vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx:::xvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#+++#######################v",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv##########T##########vvvvvvvvvvvvv#....,,,.vv~~.............#v",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#.................;;#vvvvvvvvvvvvv#....,,,vvvv~.............#v",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;............;;;;#vvvvvvvvvvvvv#....,,,vvvv~.;;;;;;;;....#v",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;..........;;;;;#vvvvvvvvvvvvv#....,,,vvv~~...;;;;;..Ycu#v",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;;.....;;;;;;;#vvvvvvvvvvvvv#...,,,,vvv~~;;;;;;;;;....#v",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;;;;;;;;;;;;;;#vvvvvvvvvvvvv#,,,,,,,.vvv~.............#v",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;;;;;;;;;;;;;;#vvvvvvvvvvvvv#,,,,,,,.vvv~.............#v",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;;;;c;;;;;;;;;#vvvvvvvvvvvvv###########################v",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;.;;;;;;;;;;;;#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv##;;;;;;.;;;;;.;;;;;;##vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;;;...s.....;;;;;#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#;;;;;.............;;;#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#######################vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
  ]
});
